export default [
    {
        id: 1,
        flightNo: 'KE7385',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '08:15',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '15:30',
        duration: '7시간 15분',
        direct: true,
        baggage: '미포함',
        price: 638866,
        slug: 'ke7385-김포-방콕',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 2,
        flightNo: 'KE8480',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '03:15',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '10:45',
        duration: '7시간 30분',
        direct: false,
        baggage: '포함',
        price: 619735,
        slug: 'ke8480-김포-괌',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 3,
        flightNo: 'KE5182',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '10:30',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '12:15',
        duration: '2시간 45분',
        direct: true,
        baggage: '포함',
        price: 151468,
        slug: 'ke5182-김포-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 4,
        flightNo: 'KE1362',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '02:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '06:15',
        duration: '4시간',
        direct: true,
        baggage: '미포함',
        price: 523876,
        slug: 'ke1362-김포-나트랑',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 5,
        flightNo: 'KE6994',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '10:45',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '15:00',
        duration: '5시간 15분',
        direct: true,
        baggage: '포함',
        price: 204196,
        slug: 'ke6994-김포-다낭',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 6,
        flightNo: 'KE4071',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '05:30',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '10:45',
        duration: '5시간 15분',
        direct: true,
        baggage: '포함',
        price: 385200,
        slug: 'ke4071-김포-오사카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 7,
        flightNo: 'KE5690',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '15:15',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '21:15',
        duration: '6시간',
        direct: true,
        baggage: '미포함',
        price: 468528,
        slug: 'ke5690-김포-후쿠오카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 8,
        flightNo: 'KE7745',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '19:45',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '00:00',
        duration: '5시간 15분',
        direct: true,
        baggage: '미포함',
        price: 470090,
        slug: 'ke7745-김포-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 9,
        flightNo: 'KE8126',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '18:30',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '00:45',
        duration: '6시간 15분',
        direct: true,
        baggage: '미포함',
        price: 225158,
        slug: 'ke8126-인천-방콕',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 10,
        flightNo: 'KE6477',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '09:00',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '11:00',
        duration: '2시간',
        direct: true,
        baggage: '미포함',
        price: 236990,
        slug: 'ke6477-인천-괌',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 11,
        flightNo: 'KE8080',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '09:15',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '12:45',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 341523,
        slug: 'ke8080-인천-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 12,
        flightNo: 'KE2591',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '05:00',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '09:15',
        duration: '4시간 15분',
        direct: true,
        baggage: '포함',
        price: 489779,
        slug: 'ke2591-인천-나트랑',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 13,
        flightNo: 'KE4364',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '13:45',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '18:45',
        duration: '5시간',
        direct: true,
        baggage: '포함',
        price: 522517,
        slug: 'ke4364-인천-다낭',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 14,
        flightNo: 'KE7498',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '18:30',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '00:45',
        duration: '6시간 15분',
        direct: true,
        baggage: '포함',
        price: 434455,
        slug: 'ke7498-인천-오사카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 15,
        flightNo: 'KE5761',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '17:30',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '19:15',
        duration: '2시간 45분',
        direct: true,
        baggage: '포함',
        price: 153181,
        slug: 'ke5761-인천-후쿠오카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 16,
        flightNo: 'KE1797',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '23:45',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '01:45',
        duration: '2시간',
        direct: true,
        baggage: '미포함',
        price: 273394,
        slug: 'ke1797-인천-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 17,
        flightNo: 'KE9648',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '23:15',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '02:30',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 622946,
        slug: 'ke9648-제주-방콕',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 18,
        flightNo: 'KE3995',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '00:15',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '05:15',
        duration: '5시간',
        direct: true,
        baggage: '미포함',
        price: 300516,
        slug: 'ke3995-제주-괌',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 19,
        flightNo: 'KE128',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '15:00',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '21:45',
        duration: '6시간 45분',
        direct: true,
        baggage: '포함',
        price: 424747,
        slug: 'ke128-제주-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 20,
        flightNo: 'KE8328',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '12:30',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '17:15',
        duration: '5시간 45분',
        direct: true,
        baggage: '미포함',
        price: 197039,
        slug: 'ke8328-제주-나트랑',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 21,
        flightNo: 'KE895',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '09:00',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '15:00',
        duration: '6시간',
        direct: true,
        baggage: '포함',
        price: 557680,
        slug: 'ke895-제주-다낭',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 22,
        flightNo: 'KE8574',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '15:00',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '22:15',
        duration: '7시간 15분',
        direct: true,
        baggage: '포함',
        price: 276663,
        slug: 'ke8574-제주-오사카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 23,
        flightNo: 'KE9938',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '08:45',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '12:15',
        duration: '4시간 30분',
        direct: true,
        baggage: '미포함',
        price: 281890,
        slug: 'ke9938-제주-후쿠오카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 24,
        flightNo: 'KE8227',
        airline: '대한항공',
        logo: '/images/airport/koreanair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '04:30',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '11:30',
        duration: '7시간',
        direct: true,
        baggage: '포함',
        price: 598159,
        slug: 'ke8227-제주-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 25,
        flightNo: 'BX6680',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '09:30',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '15:00',
        duration: '6시간 30분',
        direct: true,
        baggage: '미포함',
        price: 603703,
        slug: 'bx6680-김포-방콕',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 26,
        flightNo: 'BX3879',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '07:45',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '13:00',
        duration: '6시간 15분',
        direct: true,
        baggage: '포함',
        price: 607155,
        slug: 'bx3879-김포-괌',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 27,
        flightNo: 'BX278',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '04:30',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '11:00',
        duration: '7시간 30분',
        direct: true,
        baggage: '미포함',
        price: 225329,
        slug: 'bx278-김포-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 28,
        flightNo: 'BX4066',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '12:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '14:15',
        duration: '2시간',
        direct: true,
        baggage: '미포함',
        price: 547824,
        slug: 'bx4066-김포-나트랑',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 29,
        flightNo: 'BX6860',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '09:00',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '11:15',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 510092,
        slug: 'bx6860-김포-다낭',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 30,
        flightNo: 'BX3118',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '10:45',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '17:00',
        duration: '7시간 15분',
        direct: true,
        baggage: '미포함',
        price: 507269,
        slug: 'bx3118-김포-오사카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석, 일등석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 31,
        flightNo: 'BX5593',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '11:00',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '15:00',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 345600,
        slug: 'bx5593-김포-후쿠오카',
        seatClasses: '일반석, 프리미엄 일반석, 비즈니스석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 32,
        flightNo: 'BX7731',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '18:30',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '23:45',
        duration: '5시간 15분',
        direct: true,
        baggage: '미포함',
        price: 421300,
        slug: 'bx7731-김포-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 33,
        flightNo: 'BX6612',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '07:15',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:15',
        duration: '5시간',
        direct: true,
        baggage: '포함',
        price: 398500,
        slug: 'bx6612-인천-방콕',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 34,
        flightNo: 'BX4590',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '10:15',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '15:30',
        duration: '5시간 15분',
        direct: true,
        baggage: '포함',
        price: 412800,
        slug: 'bx4590-인천-괌',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 35,
        flightNo: 'BX2354',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '13:20',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '18:15',
        duration: '4시간 55분',
        direct: true,
        baggage: '미포함',
        price: 287900,
        slug: 'bx2354-인천-싱가포르',
        seatClasses: '일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 36,
        flightNo: 'BX1889',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '20:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '00:30',
        duration: '3시간 45분',
        direct: true,
        baggage: '포함',
        price: 332600,
        slug: 'bx1889-인천-나트랑',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 37,
        flightNo: 'BX9220',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '08:15',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '11:30',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 315400,
        slug: 'bx9220-인천-다낭',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 38,
        flightNo: 'BX3601',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '09:00',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '11:15',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 265800,
        slug: 'bx3601-인천-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 39,
        flightNo: 'BX4811',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '17:45',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '20:15',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 253400,
        slug: 'bx4811-인천-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 40,
        flightNo: 'BX1770',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '11:30',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '15:30',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 389500,
        slug: 'bx1770-인천-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 41,
        flightNo: 'BX2892',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '07:00',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '10:30',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 478200,
        slug: 'bx2892-제주-방콕',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 42,
        flightNo: 'BX9041',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '13:20',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '17:00',
        duration: '3시간 40분',
        direct: true,
        baggage: '미포함',
        price: 356800,
        slug: 'bx9041-제주-괌',
        seatClasses: '일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 43,
        flightNo: 'BX3275',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '09:30',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '13:00',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 412900,
        slug: 'bx3275-제주-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 44,
        flightNo: 'BX6182',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '18:00',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '21:00',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 395500,
        slug: 'bx6182-제주-나트랑',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 45,
        flightNo: 'BX7402',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '06:45',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '10:15',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 376200,
        slug: 'bx7402-제주-다낭',
        seatClasses: '일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 46,
        flightNo: 'BX8830',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '15:30',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '18:00',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 289400,
        slug: 'bx8830-제주-오사카',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 47,
        flightNo: 'BX5129',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '11:15',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '13:15',
        duration: '2시간',
        direct: true,
        baggage: '포함',
        price: 274800,
        slug: 'bx5129-제주-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 48,
        flightNo: 'BX6910',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '20:00',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '23:30',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 421700,
        slug: 'bx6910-제주-코타키나발루',
        seatClasses: '일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 49,
        flightNo: 'BX2020',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '07:45',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:00',
        duration: '4시간 15분',
        direct: true,
        baggage: '포함',
        price: 389600,
        slug: 'bx2020-김포-방콕',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 50,
        flightNo: 'BX3312',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '14:30',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '20:00',
        duration: '5시간 30분',
        direct: true,
        baggage: '포함',
        price: 447200,
        slug: 'bx3312-김포-괌',
        seatClasses: '일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 51,
        flightNo: 'BX4401',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '11:15',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '15:00',
        duration: '3시간 45분',
        direct: true,
        baggage: '포함',
        price: 423500,
        slug: 'bx4401-김포-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 52,
        flightNo: 'BX8820',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '06:30',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '10:00',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 389200,
        slug: 'bx8820-김포-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 53,
        flightNo: 'BX7707',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '20:15',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '23:30',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 405800,
        slug: 'bx7707-김포-다낭',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 54,
        flightNo: 'BX2689',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '09:30',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '11:45',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 298700,
        slug: 'bx2689-김포-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 55,
        flightNo: 'BX1402',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '15:10',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '16:45',
        duration: '1시간 35분',
        direct: true,
        baggage: '포함',
        price: 276500,
        slug: 'bx1402-김포-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 56,
        flightNo: 'BX6605',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '12:00',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '16:00',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 433200,
        slug: 'bx6605-김포-코타키나발루',
        seatClasses: '일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 57,
        flightNo: 'BX7329',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '08:15',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:15',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 412400,
        slug: 'bx7329-인천-방콕',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 58,
        flightNo: 'BX3008',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '22:30',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '04:00',
        duration: '5시간 30분',
        direct: true,
        baggage: '포함',
        price: 463800,
        slug: 'bx3008-인천-괌',
        seatClasses: '일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 59,
        flightNo: 'BX4315',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '17:00',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '20:30',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 428900,
        slug: 'bx4315-인천-싱가포르',
        seatClasses: '일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 60,
        flightNo: 'BX9033',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '06:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '10:00',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 401200,
        slug: 'bx9033-인천-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 61,
        flightNo: 'BX5521',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '14:30',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '17:45',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 418600,
        slug: 'bx5521-인천-다낭',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 62,
        flightNo: 'BX2390',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '19:00',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '21:00',
        duration: '2시간',
        direct: true,
        baggage: '포함',
        price: 305000,
        slug: 'bx2390-인천-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 63,
        flightNo: 'BX7771',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '11:15',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '12:50',
        duration: '1시간 35분',
        direct: true,
        baggage: '포함',
        price: 288400,
        slug: 'bx7771-인천-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 64,
        flightNo: 'BX6612',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '21:30',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '01:30',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 449500,
        slug: 'bx6612-인천-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 65,
        flightNo: 'BX5527',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '08:00',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:00',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 437800,
        slug: 'bx5527-제주-방콕',
        seatClasses: '일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 66,
        flightNo: 'BX8399',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '13:00',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '17:30',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 469000,
        slug: 'bx8399-제주-괌',
        seatClasses: '일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 67,
        flightNo: 'BX4421',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '15:00',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '19:00',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 452600,
        slug: 'bx4421-제주-싱가포르',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 68,
        flightNo: 'BX5599',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '17:30',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '20:30',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 421300,
        slug: 'bx5599-제주-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 69,
        flightNo: 'BX6150',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '09:15',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '12:30',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 436200,
        slug: 'bx6150-제주-다낭',
        seatClasses: '일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 70,
        flightNo: 'BX7702',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '10:45',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '13:15',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 308500,
        slug: 'bx7702-제주-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 71,
        flightNo: 'BX9901',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '14:30',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '16:00',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 292000,
        slug: 'bx9901-제주-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 72,
        flightNo: 'BX6601',
        airline: '에어서울',
        logo: '/images/airport/airseoul.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '20:45',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '01:15',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 459800,
        slug: 'bx6601-제주-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 73,
        flightNo: 'LJ3001',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '07:00',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '11:30',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 445000,
        slug: 'lj3001-김포-방콕',
        seatClasses: '일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 74,
        flightNo: 'LJ4065',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '10:15',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '15:00',
        duration: '4시간 45분',
        direct: true,
        baggage: '포함',
        price: 471000,
        slug: 'lj4065-김포-괌',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 75,
        flightNo: 'LJ2821',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '14:00',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '17:30',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 432200,
        slug: 'lj2821-김포-싱가포르',
        seatClasses: '일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },

    {
        id: 76,
        flightNo: 'LJ5119',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '16:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '19:15',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 418900,
        slug: 'lj5119-김포-나트랑',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 77,
        flightNo: 'LJ6298',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '12:30',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '15:30',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 439700,
        slug: 'lj6298-김포-다낭',
        seatClasses: '일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 78,
        flightNo: 'LJ2270',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '18:00',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '20:15',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 310800,
        slug: 'lj2270-김포-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 79,
        flightNo: 'LJ6111',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '20:00',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '21:30',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 285000,
        slug: 'lj6111-김포-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 80,
        flightNo: 'LJ8821',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '23:00',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '03:30',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 452000,
        slug: 'lj8821-김포-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 81,
        flightNo: 'LJ3009',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '07:15',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '11:45',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 448200,
        slug: 'lj3009-인천-방콕',
        seatClasses: '일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 82,
        flightNo: 'LJ6119',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '10:45',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '15:15',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 475000,
        slug: 'lj6119-인천-괌',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 83,
        flightNo: 'LJ4801',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '13:30',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '17:00',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 439600,
        slug: 'lj4801-인천-싱가포르',
        seatClasses: '일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 84,
        flightNo: 'LJ5211',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '15:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '18:15',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 424800,
        slug: 'lj5211-인천-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 85,
        flightNo: 'LJ6588',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '12:15',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '15:15',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 445500,
        slug: 'lj6588-인천-다낭',
        seatClasses: '일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 86,
        flightNo: 'LJ2301',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '18:30',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '20:45',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 315200,
        slug: 'lj2301-인천-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 87,
        flightNo: 'LJ6011',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '20:15',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '21:45',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 288800,
        slug: 'lj6011-인천-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 88,
        flightNo: 'LJ8400',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '22:30',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '02:30',
        duration: '4시간',
        direct: true,
        baggage: '포함',
        price: 457600,
        slug: 'lj8400-인천-코타키나발루',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 89,
        flightNo: 'LJ7210',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '09:00',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '13:30',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 442000,
        slug: 'lj7210-제주-방콕',
        seatClasses: '일반석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 90,
        flightNo: 'LJ6405',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '12:30',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '17:15',
        duration: '4시간 45분',
        direct: true,
        baggage: '포함',
        price: 468000,
        slug: 'lj6405-제주-괌',
        seatClasses: '일반석, 프리미엄 일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 91,
        flightNo: 'LJ4888',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '15:15',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '19:00',
        duration: '3시간 45분',
        direct: true,
        baggage: '포함',
        price: 455300,
        slug: 'lj4888-제주-싱가포르',
        seatClasses: '일반석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 92,
        flightNo: 'LJ5005',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '18:30',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '21:00',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 426000,
        slug: 'lj5005-제주-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 93,
        flightNo: 'LJ6603',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '09:30',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '12:45',
        duration: '3시간 15분',
        direct: true,
        baggage: '포함',
        price: 439200,
        slug: 'lj6603-제주-다낭',
        seatClasses: '일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 94,
        flightNo: 'LJ2415',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '11:30',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '13:45',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 318000,
        slug: 'lj2415-제주-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 95,
        flightNo: 'LJ6009',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '14:15',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '15:45',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 289000,
        slug: 'lj6009-제주-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 96,
        flightNo: 'LJ8700',
        airline: '진에어',
        logo: '/images/airport/jinair.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '22:00',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '02:30',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 460500,
        slug: 'lj8700-제주-코타키나발루',
        seatClasses: '일반석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 97,
        flightNo: 'OZ7210',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '07:30',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:00',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 622000,
        slug: 'oz7210-김포-방콕',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 98,
        flightNo: 'OZ8405',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '10:00',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '15:00',
        duration: '5시간',
        direct: true,
        baggage: '포함',
        price: 611000,
        slug: 'oz8405-김포-괌',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 99,
        flightNo: 'OZ4801',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '13:15',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '16:45',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 587000,
        slug: 'oz4801-김포-싱가포르',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 100,
        flightNo: 'OZ5302',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '15:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '18:15',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 576000,
        slug: 'oz5302-김포-나트랑',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 101,
        flightNo: 'OZ6400',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '11:30',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '14:30',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 589000,
        slug: 'oz6400-김포-다낭',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 102,
        flightNo: 'OZ2305',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '18:00',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '20:15',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 418000,
        slug: 'oz2305-김포-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 103,
        flightNo: 'OZ6002',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '20:30',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '22:00',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 388000,
        slug: 'oz6002-김포-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 104,
        flightNo: 'OZ8701',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '김포 국제공항',
        departCode: '서울(김포)(GMP)',
        departureTime: '22:45',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '03:15',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 605000,
        slug: 'oz8701-김포-코타키나발루',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 105,
        flightNo: 'OZ3002',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '08:15',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:45',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 628000,
        slug: 'oz3002-인천-방콕',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 106,
        flightNo: 'OZ8409',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '11:00',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '16:00',
        duration: '5시간',
        direct: true,
        baggage: '포함',
        price: 615000,
        slug: 'oz8409-인천-괌',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 107,
        flightNo: 'OZ4803',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '13:45',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '17:15',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 598000,
        slug: 'oz4803-인천-싱가포르',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 108,
        flightNo: 'OZ5311',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '16:00',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '18:30',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 579000,
        slug: 'oz5311-인천-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 109,
        flightNo: 'OZ6502',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '12:00',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '15:00',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 590000,
        slug: 'oz6502-인천-다낭',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 110,
        flightNo: 'OZ2311',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '18:45',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '21:00',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 422000,
        slug: 'oz2311-인천-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 111,
        flightNo: 'OZ6005',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '20:45',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '22:15',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 390000,
        slug: 'oz6005-인천-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 112,
        flightNo: 'OZ8705',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '인천 국제공항 - 터미널 2',
        departCode: '서울(인천)(ICN)',
        departureTime: '22:15',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '02:45',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 608000,
        slug: 'oz8705-인천-코타키나발루',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
    {
        id: 113,
        flightNo: 'OZ3201',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '07:30',
        arrivalAirport: '수완나품 국제공항',
        arriveCode: '방콕(BKK)',
        arrivalTime: '12:00',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 620000,
        slug: 'oz3201-제주-방콕',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/bangkok1.jpg',
    },
    {
        id: 114,
        flightNo: 'OZ8407',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '10:00',
        arrivalAirport: '괌 국제공항',
        arriveCode: '괌(GUM)',
        arrivalTime: '15:00',
        duration: '5시간',
        direct: true,
        baggage: '포함',
        price: 609000,
        slug: 'oz8407-제주-괌',
        seatClasses: '일반석',
        images: '/images/airport/detail/guam1.jpg',
    },
    {
        id: 115,
        flightNo: 'OZ4820',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '13:15',
        arrivalAirport: '창이 국제공항',
        arriveCode: '싱가포르(SIN)',
        arrivalTime: '16:45',
        duration: '3시간 30분',
        direct: true,
        baggage: '포함',
        price: 586000,
        slug: 'oz4820-제주-싱가포르',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/singapore1.jpg',
    },
    {
        id: 116,
        flightNo: 'OZ5321',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '15:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        arriveCode: '나트랑(CXR)',
        arrivalTime: '18:15',
        duration: '2시간 30분',
        direct: true,
        baggage: '포함',
        price: 575000,
        slug: 'oz5321-제주-나트랑',
        seatClasses: '일반석',
        images: '/images/airport/detail/nha-trang1.jpg',
    },
    {
        id: 117,
        flightNo: 'OZ6507',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '11:30',
        arrivalAirport: '다낭 국제공항',
        arriveCode: '다낭(DAD)',
        arrivalTime: '14:30',
        duration: '3시간',
        direct: true,
        baggage: '포함',
        price: 588000,
        slug: 'oz6507-제주-다낭',
        seatClasses: '일반석',
        images: '/images/airport/detail/danang1.jpg',
    },
    {
        id: 118,
        flightNo: 'OZ2315',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '18:00',
        arrivalAirport: '간사이 국제공항',
        arriveCode: '오사카(KIX)',
        arrivalTime: '20:15',
        duration: '2시간 15분',
        direct: true,
        baggage: '포함',
        price: 420000,
        slug: 'oz2315-제주-오사카',
        seatClasses: '일반석',
        images: '/images/airport/detail/osaka1.jpg',
    },
    {
        id: 119,
        flightNo: 'OZ6007',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '20:15',
        arrivalAirport: '후쿠오카 국제공항',
        arriveCode: '후쿠오카(FUK)',
        arrivalTime: '21:45',
        duration: '1시간 30분',
        direct: true,
        baggage: '포함',
        price: 387000,
        slug: 'oz6007-제주-후쿠오카',
        seatClasses: '일반석',
        images: '/images/airport/detail/fukuoka1.jpg',
    },
    {
        id: 120,
        flightNo: 'OZ8709',
        airline: '아시아나항공',
        logo: '/images/airport/asiana.png',
        departureAirport: '제주 국제공항',
        departCode: '제주(CJU)',
        departureTime: '22:30',
        arrivalAirport: '코타키나발루 국제공항',
        arriveCode: '코타키나발루(BKI)',
        arrivalTime: '03:00',
        duration: '4시간 30분',
        direct: true,
        baggage: '포함',
        price: 607000,
        slug: 'oz8709-제주-코타키나발루',
        seatClasses: '일반석, 비즈니스석',
        images: '/images/airport/detail/kota-kinabalu1.jpg',
    },
];
