export default [
  {
    id: 1,
    flightNo: "KE7385",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "08:15",
    arrivalAirport: "수완나품 국제공항",
    arrivalTime: "15:30",
    duration: "7시간 15분",
    direct: true,
    baggage: "미포함",
    price: 638866,
    slug: "ke7385-김포-방콕",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/bangkok1.jpg",
  },
  {
    id: 2,
    flightNo: "KE8480",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "03:15",
    arrivalAirport: "괌 국제공항",
    arrivalTime: "10:45",
    duration: "7시간 30분",
    direct: false,
    baggage: "포함",
    price: 619735,
    slug: "ke8480-김포-괌",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/guam1.jpg",
  },
  {
    id: 3,
    flightNo: "KE5182",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "10:30",
    arrivalAirport: "창이 국제공항",
    arrivalTime: "12:15",
    duration: "2시간 45분",
    direct: true,
    baggage: "포함",
    price: 151468,
    slug: "ke5182-김포-싱가포르",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/singapore1.jpg",
  },
  {
    id: 4,
    flightNo: "KE1362",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "02:15",
    arrivalAirport: "나트랑 깜라인 국제공항",
    arrivalTime: "06:15",
    duration: "4시간",
    direct: true,
    baggage: "미포함",
    price: 523876,
    slug: "ke1362-김포-나트랑",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/nha-trang1.jpg",
  },
  {
    id: 5,
    flightNo: "KE6994",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "10:45",
    arrivalAirport: "다낭 국제공항",
    arrivalTime: "15:00",
    duration: "5시간 15분",
    direct: true,
    baggage: "포함",
    price: 204196,
    slug: "ke6994-김포-다낭",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/danang1.jpg",
  },
  {
    id: 6,
    flightNo: "KE4071",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "05:30",
    arrivalAirport: "간사이 국제공항",
    arrivalTime: "10:45",
    duration: "5시간 15분",
    direct: true,
    baggage: "포함",
    price: 385200,
    slug: "ke4071-김포-오사카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/osaka1.jpg",
  },
  {
    id: 7,
    flightNo: "KE5690",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "15:15",
    arrivalAirport: "후쿠오카 국제공항",
    arrivalTime: "21:15",
    duration: "6시간",
    direct: true,
    baggage: "미포함",
    price: 468528,
    slug: "ke5690-김포-후쿠오카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/fukuoka1.jpg",
  },
  {
    id: 8,
    flightNo: "KE7745",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "김포 국제공항",
    departureTime: "19:45",
    arrivalAirport: "코타키나발루 국제공항",
    arrivalTime: "00:00",
    duration: "5시간 15분",
    direct: true,
    baggage: "미포함",
    price: 470090,
    slug: "ke7745-김포-코타키나발루",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/kota-kinabalu1.jpg",
  },
  {
    id: 9,
    flightNo: "KE8126",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "18:30",
    arrivalAirport: "수완나품 국제공항",
    arrivalTime: "00:45",
    duration: "6시간 15분",
    direct: true,
    baggage: "미포함",
    price: 225158,
    slug: "ke8126-인천-방콕",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/bangkok1.jpg",
  },
  {
    id: 10,
    flightNo: "KE6477",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "09:00",
    arrivalAirport: "괌 국제공항",
    arrivalTime: "11:00",
    duration: "2시간",
    direct: true,
    baggage: "미포함",
    price: 236990,
    slug: "ke6477-인천-괌",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/guam1.jpg",
  },
  {
    id: 11,
    flightNo: "KE8080",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "09:15",
    arrivalAirport: "창이 국제공항",
    arrivalTime: "12:45",
    duration: "3시간 30분",
    direct: true,
    baggage: "포함",
    price: 341523,
    slug: "ke8080-인천-싱가포르",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/singapore1.jpg",
  },
  {
    id: 12,
    flightNo: "KE2591",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "05:00",
    arrivalAirport: "나트랑 깜라인 국제공항",
    arrivalTime: "09:15",
    duration: "4시간 15분",
    direct: true,
    baggage: "포함",
    price: 489779,
    slug: "ke2591-인천-나트랑",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/nha-trang1.jpg",
  },
  {
    id: 13,
    flightNo: "KE4364",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "13:45",
    arrivalAirport: "다낭 국제공항",
    arrivalTime: "18:45",
    duration: "5시간",
    direct: true,
    baggage: "포함",
    price: 522517,
    slug: "ke4364-인천-다낭",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/danang1.jpg",
  },
  {
    id: 14,
    flightNo: "KE7498",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "18:30",
    arrivalAirport: "간사이 국제공항",
    arrivalTime: "00:45",
    duration: "6시간 15분",
    direct: true,
    baggage: "포함",
    price: 434455,
    slug: "ke7498-인천-오사카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/osaka1.jpg",
  },
  {
    id: 15,
    flightNo: "KE5761",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "17:30",
    arrivalAirport: "후쿠오카 국제공항",
    arrivalTime: "19:15",
    duration: "2시간 45분",
    direct: true,
    baggage: "포함",
    price: 153181,
    slug: "ke5761-인천-후쿠오카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/fukuoka1.jpg",
  },
  {
    id: 16,
    flightNo: "KE1797",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "인천 국제공항 - 터미널 2",
    departureTime: "23:45",
    arrivalAirport: "코타키나발루 국제공항",
    arrivalTime: "01:45",
    duration: "2시간",
    direct: true,
    baggage: "미포함",
    price: 273394,
    slug: "ke1797-인천-코타키나발루",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/kota-kinabalu1.jpg",
  },
  {
    id: 17,
    flightNo: "KE9648",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "23:15",
    arrivalAirport: "수완나품 국제공항",
    arrivalTime: "02:30",
    duration: "3시간 15분",
    direct: true,
    baggage: "포함",
    price: 622946,
    slug: "ke9648-제주-방콕",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/bangkok1.jpg",
  },
  {
    id: 18,
    flightNo: "KE3995",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "00:15",
    arrivalAirport: "괌 국제공항",
    arrivalTime: "05:15",
    duration: "5시간",
    direct: true,
    baggage: "미포함",
    price: 300516,
    slug: "ke3995-제주-괌",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/guam1.jpg",
  },
  {
    id: 19,
    flightNo: "KE128",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "15:00",
    arrivalAirport: "창이 국제공항",
    arrivalTime: "21:45",
    duration: "6시간 45분",
    direct: true,
    baggage: "포함",
    price: 424747,
    slug: "ke128-제주-싱가포르",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/singapore1.jpg",
  },
  {
    id: 20,
    flightNo: "KE8328",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "12:30",
    arrivalAirport: "나트랑 깜라인 국제공항",
    arrivalTime: "17:15",
    duration: "5시간 45분",
    direct: true,
    baggage: "미포함",
    price: 197039,
    slug: "ke8328-제주-나트랑",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/nha-trang1.jpg",
  },
  {
    id: 21,
    flightNo: "KE895",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "09:00",
    arrivalAirport: "다낭 국제공항",
    arrivalTime: "15:00",
    duration: "6시간",
    direct: true,
    baggage: "포함",
    price: 557680,
    slug: "ke895-제주-다낭",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/danang1.jpg",
  },
  {
    id: 22,
    flightNo: "KE8574",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "15:00",
    arrivalAirport: "간사이 국제공항",
    arrivalTime: "22:15",
    duration: "7시간 15분",
    direct: true,
    baggage: "포함",
    price: 276663,
    slug: "ke8574-제주-오사카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/osaka1.jpg",
  },
  {
    id: 23,
    flightNo: "KE9938",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "08:45",
    arrivalAirport: "후쿠오카 국제공항",
    arrivalTime: "12:15",
    duration: "4시간 30분",
    direct: true,
    baggage: "미포함",
    price: 281890,
    slug: "ke9938-제주-후쿠오카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/fukuoka1.jpg",
  },
  {
    id: 24,
    flightNo: "KE8227",
    airline: "대한항공",
    logo: "/images/airport/koreanair.png",
    departureAirport: "제주 국제공항",
    departureTime: "04:30",
    arrivalAirport: "코타키나발루 국제공항",
    arrivalTime: "11:30",
    duration: "7시간",
    direct: true,
    baggage: "포함",
    price: 598159,
    slug: "ke8227-제주-코타키나발루",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/kota-kinabalu1.jpg",
  },
  {
    id: 25,
    flightNo: "BX6680",
    airline: "에어서울",
    logo: "/images/airport/airseoul.png",
    departureAirport: "김포 국제공항",
    departureTime: "09:30",
    arrivalAirport: "수완나품 국제공항",
    arrivalTime: "15:00",
    duration: "6시간 30분",
    direct: true,
    baggage: "미포함",
    price: 603703,
    slug: "bx6680-김포-방콕",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/bangkok1.jpg",
  },
  {
    id: 26,
    flightNo: "BX3879",
    airline: "에어서울",
    logo: "/images/airport/airseoul.png",
    departureAirport: "김포 국제공항",
    departureTime: "07:45",
    arrivalAirport: "괌 국제공항",
    arrivalTime: "13:00",
    duration: "6시간 15분",
    direct: true,
    baggage: "포함",
    price: 607155,
    slug: "bx3879-김포-괌",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/guam1.jpg",
  },
  {
    id: 27,
    flightNo: "BX278",
    airline: "에어서울",
    logo: "/images/airport/airseoul.png",
    departureAirport: "김포 국제공항",
    departureTime: "04:30",
    arrivalAirport: "창이 국제공항",
    arrivalTime: "11:00",
    duration: "7시간 30분",
    direct: true,
    baggage: "미포함",
    price: 225329,
    slug: "bx278-김포-싱가포르",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/singapore1.jpg",
  },
  {
    id: 28,
    flightNo: "BX4066",
    airline: "에어서울",
    logo: "/images/airport/airseoul.png",
    departureAirport: "김포 국제공항",
    departureTime: "12:15",
    arrivalAirport: "나트랑 깜라인 국제공항",
    arrivalTime: "14:15",
    duration: "2시간",
    direct: true,
    baggage: "미포함",
    price: 547824,
    slug: "bx4066-김포-나트랑",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/nha-trang1.jpg",
  },
  {
    id: 29,
    flightNo: "BX6860",
    airline: "에어서울",
    logo: "/images/airport/airseoul.png",
    departureAirport: "김포 국제공항",
    departureTime: "09:00",
    arrivalAirport: "다낭 국제공항",
    arrivalTime: "11:15",
    duration: "2시간 15분",
    direct: true,
    baggage: "포함",
    price: 510092,
    slug: "bx6860-김포-다낭",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/danang1.jpg",
  },
  {
    id: 30,
    flightNo: "BX3118",
    airline: "에어서울",
    logo: "/images/airport/airseoul.png",
    departureAirport: "김포 국제공항",
    departureTime: "10:45",
    arrivalAirport: "간사이 국제공항",
    arrivalTime: "17:00",
    duration: "7시간 15분",
    direct: true,
    baggage: "미포함",
    price: 507269,
    slug: "bx3118-김포-오사카",
    seatClasses: "일반석, 프리미엄 일반석, 비즈니스석, 일등석",
    images: "/images/airport/detail/osaka1.jpg",
  },
];
