export default [
    {
        id: 1,
        airline: '대한항공',
        flightNo: 'KE7385',
        logo: '/images/airport/koreanair.png',
        departureTime: '08:15',
        departureAirport: '김포 국제공항',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '15:30',
        arrivalAirport: '수완나품 국제공항',
        price: 638866,
        slug: 'ke7385-김포-방콕',
        baggage: '미포함',
    },
    {
        id: 2,
        airline: '대한항공',
        flightNo: 'KE8480',
        logo: '/images/airport/koreanair.png',
        departureTime: '03:15',
        departureAirport: '김포 국제공항',
        duration: '7시간 30분',
        direct: false,
        arrivalTime: '10:45',
        arrivalAirport: '괌 국제공항',
        price: 619735,
        slug: 'ke8480-김포-괌',
        baggage: '포함',
    },
    {
        id: 3,
        airline: '대한항공',
        flightNo: 'KE5182',
        logo: '/images/airport/koreanair.png',
        departureTime: '10:30',
        departureAirport: '김포 국제공항',
        duration: '2시간 45분',
        direct: true,
        arrivalTime: '12:15',
        arrivalAirport: '창이 국제공항',
        price: 151468,
        slug: 'ke5182-김포-싱가포르',
        baggage: '포함',
    },
    {
        id: 4,
        airline: '대한항공',
        flightNo: 'KE1362',
        logo: '/images/airport/koreanair.png',
        departureTime: '02:15',
        departureAirport: '김포 국제공항',
        duration: '4시간',
        direct: true,
        arrivalTime: '06:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 523876,
        slug: 'ke1362-김포-나트랑',
        baggage: '미포함',
    },
    {
        id: 5,
        airline: '대한항공',
        flightNo: 'KE6994',
        logo: '/images/airport/koreanair.png',
        departureTime: '10:45',
        departureAirport: '김포 국제공항',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '15:00',
        arrivalAirport: '다낭 국제공항',
        price: 204196,
        slug: 'ke6994-김포-다낭',
        baggage: '포함',
    },
    {
        id: 6,
        airline: '대한항공',
        flightNo: 'KE4071',
        logo: '/images/airport/koreanair.png',
        departureTime: '05:30',
        departureAirport: '김포 국제공항',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '10:45',
        arrivalAirport: '간사이 국제공항',
        price: 385200,
        slug: 'ke4071-김포-오사카',
        baggage: '포함',
    },
    {
        id: 7,
        airline: '대한항공',
        flightNo: 'KE5690',
        logo: '/images/airport/koreanair.png',
        departureTime: '15:15',
        departureAirport: '김포 국제공항',
        duration: '6시간',
        direct: true,
        arrivalTime: '21:15',
        arrivalAirport: '후쿠오카 국제공항',
        price: 468528,
        slug: 'ke5690-김포-후쿠오카',
        baggage: '미포함',
    },
    {
        id: 8,
        airline: '대한항공',
        flightNo: 'KE7745',
        logo: '/images/airport/koreanair.png',
        departureTime: '19:45',
        departureAirport: '김포 국제공항',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '00:00',
        arrivalAirport: '코타키나발루 국제공항',
        price: 470090,
        slug: 'ke7745-김포-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 9,
        airline: '대한항공',
        flightNo: 'KE8126',
        logo: '/images/airport/koreanair.png',
        departureTime: '18:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '00:45',
        arrivalAirport: '수완나품 국제공항',
        price: 225158,
        slug: 'ke8126-인천-방콕',
        baggage: '미포함',
    },
    {
        id: 10,
        airline: '대한항공',
        flightNo: 'KE6477',
        logo: '/images/airport/koreanair.png',
        departureTime: '09:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간',
        direct: true,
        arrivalTime: '11:00',
        arrivalAirport: '괌 국제공항',
        price: 236990,
        slug: 'ke6477-인천-괌',
        baggage: '미포함',
    },
    {
        id: 11,
        airline: '대한항공',
        flightNo: 'KE8080',
        logo: '/images/airport/koreanair.png',
        departureTime: '09:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '3시간 30분',
        direct: true,
        arrivalTime: '12:45',
        arrivalAirport: '창이 국제공항',
        price: 341523,
        slug: 'ke8080-인천-싱가포르',
        baggage: '포함',
    },
    {
        id: 12,
        airline: '대한항공',
        flightNo: 'KE2591',
        logo: '/images/airport/koreanair.png',
        departureTime: '05:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '4시간 15분',
        direct: true,
        arrivalTime: '09:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 489779,
        slug: 'ke2591-인천-나트랑',
        baggage: '포함',
    },
    {
        id: 13,
        airline: '대한항공',
        flightNo: 'KE4364',
        logo: '/images/airport/koreanair.png',
        departureTime: '13:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간',
        direct: true,
        arrivalTime: '18:45',
        arrivalAirport: '다낭 국제공항',
        price: 522517,
        slug: 'ke4364-인천-다낭',
        baggage: '포함',
    },
    {
        id: 14,
        airline: '대한항공',
        flightNo: 'KE7498',
        logo: '/images/airport/koreanair.png',
        departureTime: '18:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '00:45',
        arrivalAirport: '간사이 국제공항',
        price: 434455,
        slug: 'ke7498-인천-오사카',
        baggage: '포함',
    },
    {
        id: 15,
        airline: '대한항공',
        flightNo: 'KE5761',
        logo: '/images/airport/koreanair.png',
        departureTime: '17:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간 45분',
        direct: true,
        arrivalTime: '19:15',
        arrivalAirport: '후쿠오카 국제공항',
        price: 153181,
        slug: 'ke5761-인천-후쿠오카',
        baggage: '포함',
    },
    {
        id: 16,
        airline: '대한항공',
        flightNo: 'KE1797',
        logo: '/images/airport/koreanair.png',
        departureTime: '23:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간',
        direct: true,
        arrivalTime: '01:45',
        arrivalAirport: '코타키나발루 국제공항',
        price: 273394,
        slug: 'ke1797-인천-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 17,
        airline: '대한항공',
        flightNo: 'KE9648',
        logo: '/images/airport/koreanair.png',
        departureTime: '23:15',
        departureAirport: '제주 국제공항',
        duration: '3시간 15분',
        direct: true,
        arrivalTime: '02:30',
        arrivalAirport: '수완나품 국제공항',
        price: 622946,
        slug: 'ke9648-제주-방콕',
        baggage: '포함',
    },
    {
        id: 18,
        airline: '대한항공',
        flightNo: 'KE3995',
        logo: '/images/airport/koreanair.png',
        departureTime: '00:15',
        departureAirport: '제주 국제공항',
        duration: '5시간',
        direct: true,
        arrivalTime: '05:15',
        arrivalAirport: '괌 국제공항',
        price: 300516,
        slug: 'ke3995-제주-괌',
        baggage: '미포함',
    },
    {
        id: 19,
        airline: '대한항공',
        flightNo: 'KE128',
        logo: '/images/airport/koreanair.png',
        departureTime: '15:00',
        departureAirport: '제주 국제공항',
        duration: '6시간 45분',
        direct: true,
        arrivalTime: '21:45',
        arrivalAirport: '창이 국제공항',
        price: 424747,
        slug: 'ke128-제주-싱가포르',
        baggage: '포함',
    },
    {
        id: 20,
        airline: '대한항공',
        flightNo: 'KE8328',
        logo: '/images/airport/koreanair.png',
        departureTime: '12:30',
        departureAirport: '제주 국제공항',
        duration: '5시간 45분',
        direct: true,
        arrivalTime: '17:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 197039,
        slug: 'ke8328-제주-나트랑',
        baggage: '미포함',
    },
    {
        id: 21,
        airline: '대한항공',
        flightNo: 'KE895',
        logo: '/images/airport/koreanair.png',
        departureTime: '09:00',
        departureAirport: '제주 국제공항',
        duration: '6시간',
        direct: true,
        arrivalTime: '15:00',
        arrivalAirport: '다낭 국제공항',
        price: 557680,
        slug: 'ke895-제주-다낭',
        baggage: '포함',
    },
    {
        id: 22,
        airline: '대한항공',
        flightNo: 'KE8574',
        logo: '/images/airport/koreanair.png',
        departureTime: '15:00',
        departureAirport: '제주 국제공항',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '22:15',
        arrivalAirport: '간사이 국제공항',
        price: 276663,
        slug: 'ke8574-제주-오사카',
        baggage: '포함',
    },
    {
        id: 23,
        airline: '대한항공',
        flightNo: 'KE9938',
        logo: '/images/airport/koreanair.png',
        departureTime: '08:45',
        departureAirport: '제주 국제공항',
        duration: '4시간 30분',
        direct: true,
        arrivalTime: '12:15',
        arrivalAirport: '후쿠오카 국제공항',
        price: 281890,
        slug: 'ke9938-제주-후쿠오카',
        baggage: '미포함',
    },
    {
        id: 24,
        airline: '대한항공',
        flightNo: 'KE8227',
        logo: '/images/airport/koreanair.png',
        departureTime: '04:30',
        departureAirport: '제주 국제공항',
        duration: '7시간',
        direct: true,
        arrivalTime: '11:30',
        arrivalAirport: '코타키나발루 국제공항',
        price: 598159,
        slug: 'ke8227-제주-코타키나발루',
        baggage: '포함',
    },
    {
        id: 25,
        airline: '에어서울',
        flightNo: 'BX6680',
        logo: '/images/airport/airseoul.png',
        departureTime: '09:30',
        departureAirport: '김포 국제공항',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '15:00',
        arrivalAirport: '수완나품 국제공항',
        price: 603703,
        slug: 'bx6680-김포-방콕',
        baggage: '미포함',
    },
    {
        id: 26,
        airline: '에어서울',
        flightNo: 'BX3879',
        logo: '/images/airport/airseoul.png',
        departureTime: '07:45',
        departureAirport: '김포 국제공항',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '13:00',
        arrivalAirport: '괌 국제공항',
        price: 607155,
        slug: 'bx3879-김포-괌',
        baggage: '포함',
    },
    {
        id: 27,
        airline: '에어서울',
        flightNo: 'BX278',
        logo: '/images/airport/airseoul.png',
        departureTime: '04:30',
        departureAirport: '김포 국제공항',
        duration: '7시간 30분',
        direct: true,
        arrivalTime: '11:00',
        arrivalAirport: '창이 국제공항',
        price: 225329,
        slug: 'bx278-김포-싱가포르',
        baggage: '미포함',
    },
    {
        id: 28,
        airline: '에어서울',
        flightNo: 'BX4066',
        logo: '/images/airport/airseoul.png',
        departureTime: '12:15',
        departureAirport: '김포 국제공항',
        duration: '2시간',
        direct: true,
        arrivalTime: '14:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 547824,
        slug: 'bx4066-김포-나트랑',
        baggage: '미포함',
    },
    {
        id: 29,
        airline: '에어서울',
        flightNo: 'BX6860',
        logo: '/images/airport/airseoul.png',
        departureTime: '09:00',
        departureAirport: '김포 국제공항',
        duration: '2시간 15분',
        direct: true,
        arrivalTime: '11:15',
        arrivalAirport: '다낭 국제공항',
        price: 510092,
        slug: 'bx6860-김포-다낭',
        baggage: '포함',
    },
    {
        id: 30,
        airline: '에어서울',
        flightNo: 'BX3118',
        logo: '/images/airport/airseoul.png',
        departureTime: '10:45',
        departureAirport: '김포 국제공항',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '17:00',
        arrivalAirport: '간사이 국제공항',
        price: 507269,
        slug: 'bx3118-김포-오사카',
        baggage: '미포함',
    },
    {
        id: 31,
        airline: '에어서울',
        flightNo: 'BX9124',
        logo: '/images/airport/airseoul.png',
        departureTime: '21:00',
        departureAirport: '김포 국제공항',
        duration: '4시간 45분',
        direct: true,
        arrivalTime: '01:45',
        arrivalAirport: '후쿠오카 국제공항',
        price: 217231,
        slug: 'bx9124-김포-후쿠오카',
        baggage: '포함',
    },
    {
        id: 32,
        airline: '에어서울',
        flightNo: 'BX4869',
        logo: '/images/airport/airseoul.png',
        departureTime: '17:30',
        departureAirport: '김포 국제공항',
        duration: '5시간 30분',
        direct: true,
        arrivalTime: '22:00',
        arrivalAirport: '코타키나발루 국제공항',
        price: 178663,
        slug: 'bx4869-김포-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 33,
        airline: '에어서울',
        flightNo: 'BX4364',
        logo: '/images/airport/airseoul.png',
        departureTime: '20:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '7시간 45분',
        direct: true,
        arrivalTime: '03:30',
        arrivalAirport: '수완나품 국제공항',
        price: 413708,
        slug: 'bx4364-인천-방콕',
        baggage: '포함',
    },
    {
        id: 34,
        airline: '에어서울',
        flightNo: 'BX1388',
        logo: '/images/airport/airseoul.png',
        departureTime: '10:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '3시간',
        direct: true,
        arrivalTime: '13:15',
        arrivalAirport: '괌 국제공항',
        price: 389784,
        slug: 'bx1388-인천-괌',
        baggage: '포함',
    },
    {
        id: 35,
        airline: '에어서울',
        flightNo: 'BX5128',
        logo: '/images/airport/airseoul.png',
        departureTime: '12:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '17:45',
        arrivalAirport: '창이 국제공항',
        price: 247460,
        slug: 'bx5128-인천-싱가포르',
        baggage: '포함',
    },
    {
        id: 36,
        airline: '에어서울',
        flightNo: 'BX4612',
        logo: '/images/airport/airseoul.png',
        departureTime: '01:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '06:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 325675,
        slug: 'bx4612-인천-나트랑',
        baggage: '포함',
    },
    {
        id: 37,
        airline: '에어서울',
        flightNo: 'BX6518',
        logo: '/images/airport/airseoul.png',
        departureTime: '22:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '4시간 45분',
        direct: true,
        arrivalTime: '02:00',
        arrivalAirport: '다낭 국제공항',
        price: 431795,
        slug: 'bx6518-인천-다낭',
        baggage: '포함',
    },
    {
        id: 38,
        airline: '에어서울',
        flightNo: 'BX7686',
        logo: '/images/airport/airseoul.png',
        departureTime: '21:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '7시간 30분',
        direct: true,
        arrivalTime: '04:15',
        arrivalAirport: '간사이 국제공항',
        price: 490759,
        slug: 'bx7686-인천-오사카',
        baggage: '포함',
    },
    {
        id: 39,
        airline: '에어서울',
        flightNo: 'BX8529',
        logo: '/images/airport/airseoul.png',
        departureTime: '06:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간 30분',
        direct: true,
        arrivalTime: '11:00',
        arrivalAirport: '후쿠오카 국제공항',
        price: 267093,
        slug: 'bx8529-인천-후쿠오카',
        baggage: '미포함',
    },
    {
        id: 40,
        airline: '에어서울',
        flightNo: 'BX2098',
        logo: '/images/airport/airseoul.png',
        departureTime: '14:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '20:15',
        arrivalAirport: '코타키나발루 국제공항',
        price: 196997,
        slug: 'bx2098-인천-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 41,
        airline: '에어서울',
        flightNo: 'BX4335',
        logo: '/images/airport/airseoul.png',
        departureTime: '23:15',
        departureAirport: '제주 국제공항',
        duration: '7시간 45분',
        direct: true,
        arrivalTime: '06:00',
        arrivalAirport: '수완나품 국제공항',
        price: 525407,
        slug: 'bx4335-제주-방콕',
        baggage: '포함',
    },
    {
        id: 42,
        airline: '에어서울',
        flightNo: 'BX4571',
        logo: '/images/airport/airseoul.png',
        departureTime: '07:30',
        departureAirport: '제주 국제공항',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '14:45',
        arrivalAirport: '괌 국제공항',
        price: 464216,
        slug: 'bx4571-제주-괌',
        baggage: '포함',
    },
    {
        id: 43,
        airline: '에어서울',
        flightNo: 'BX4264',
        logo: '/images/airport/airseoul.png',
        departureTime: '18:00',
        departureAirport: '제주 국제공항',
        duration: '7시간',
        direct: true,
        arrivalTime: '01:00',
        arrivalAirport: '창이 국제공항',
        price: 605705,
        slug: 'bx4264-제주-싱가포르',
        baggage: '포함',
    },
    {
        id: 44,
        airline: '에어서울',
        flightNo: 'BX7370',
        logo: '/images/airport/airseoul.png',
        departureTime: '12:15',
        departureAirport: '제주 국제공항',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '18:30',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 548119,
        slug: 'bx7370-제주-나트랑',
        baggage: '포함',
    },
    {
        id: 45,
        airline: '에어서울',
        flightNo: 'BX5682',
        logo: '/images/airport/airseoul.png',
        departureTime: '03:45',
        departureAirport: '제주 국제공항',
        duration: '2시간',
        direct: true,
        arrivalTime: '05:45',
        arrivalAirport: '다낭 국제공항',
        price: 518706,
        slug: 'bx5682-제주-다낭',
        baggage: '미포함',
    },
    {
        id: 46,
        airline: '에어서울',
        flightNo: 'BX1739',
        logo: '/images/airport/airseoul.png',
        departureTime: '20:00',
        departureAirport: '제주 국제공항',
        duration: '3시간 15분',
        direct: true,
        arrivalTime: '23:15',
        arrivalAirport: '간사이 국제공항',
        price: 455961,
        slug: 'bx1739-제주-오사카',
        baggage: '포함',
    },
    {
        id: 47,
        airline: '에어서울',
        flightNo: 'BX995',
        logo: '/images/airport/airseoul.png',
        departureTime: '03:15',
        departureAirport: '제주 국제공항',
        duration: '5시간 30분',
        direct: true,
        arrivalTime: '08:45',
        arrivalAirport: '후쿠오카 국제공항',
        price: 318715,
        slug: 'bx995-제주-후쿠오카',
        baggage: '포함',
    },
    {
        id: 48,
        airline: '에어서울',
        flightNo: 'BX2816',
        logo: '/images/airport/airseoul.png',
        departureTime: '23:15',
        departureAirport: '제주 국제공항',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '04:30',
        arrivalAirport: '코타키나발루 국제공항',
        price: 489570,
        slug: 'bx2816-제주-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 49,
        airline: '진에어',
        flightNo: 'LJ3639',
        logo: '/images/airport/jinair.png',
        departureTime: '06:45',
        departureAirport: '김포 국제공항',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '12:00',
        arrivalAirport: '수완나품 국제공항',
        price: 394019,
        slug: 'lj3639-김포-방콕',
        baggage: '포함',
    },
    {
        id: 50,
        airline: '진에어',
        flightNo: 'LJ6606',
        logo: '/images/airport/jinair.png',
        departureTime: '12:15',
        departureAirport: '김포 국제공항',
        duration: '6시간 45분',
        direct: true,
        arrivalTime: '18:00',
        arrivalAirport: '괌 국제공항',
        price: 568532,
        slug: 'lj6606-김포-괌',
        baggage: '포함',
    },
    {
        id: 51,
        airline: '진에어',
        flightNo: 'LJ1404',
        logo: '/images/airport/jinair.png',
        departureTime: '03:00',
        departureAirport: '김포 국제공항',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '09:30',
        arrivalAirport: '창이 국제공항',
        price: 286331,
        slug: 'lj1404-김포-싱가포르',
        baggage: '포함',
    },
    {
        id: 52,
        airline: '진에어',
        flightNo: 'LJ8914',
        logo: '/images/airport/jinair.png',
        departureTime: '14:45',
        departureAirport: '김포 국제공항',
        duration: '2시간 15분',
        direct: true,
        arrivalTime: '16:00',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 564829,
        slug: 'lj8914-김포-나트랑',
        baggage: '포함',
    },
    {
        id: 53,
        airline: '진에어',
        flightNo: 'LJ1796',
        logo: '/images/airport/jinair.png',
        departureTime: '09:00',
        departureAirport: '김포 국제공항',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '14:15',
        arrivalAirport: '다낭 국제공항',
        price: 365671,
        slug: 'lj1796-김포-다낭',
        baggage: '포함',
    },
    {
        id: 54,
        airline: '진에어',
        flightNo: 'LJ7825',
        logo: '/images/airport/jinair.png',
        departureTime: '08:00',
        departureAirport: '김포 국제공항',
        duration: '2시간 45분',
        direct: true,
        arrivalTime: '10:45',
        arrivalAirport: '간사이 국제공항',
        price: 336580,
        slug: 'lj7825-김포-오사카',
        baggage: '포함',
    },
    {
        id: 55,
        airline: '진에어',
        flightNo: 'LJ8948',
        logo: '/images/airport/jinair.png',
        departureTime: '11:45',
        departureAirport: '김포 국제공항',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '17:00',
        arrivalAirport: '후쿠오카 국제공항',
        price: 535641,
        slug: 'lj8948-김포-후쿠오카',
        baggage: '포함',
    },
    {
        id: 56,
        airline: '진에어',
        flightNo: 'LJ2246',
        logo: '/images/airport/jinair.png',
        departureTime: '13:15',
        departureAirport: '김포 국제공항',
        duration: '4시간 45분',
        direct: true,
        arrivalTime: '17:00',
        arrivalAirport: '코타키나발루 국제공항',
        price: 458474,
        slug: 'lj2246-김포-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 57,
        airline: '진에어',
        flightNo: 'LJ3640',
        logo: '/images/airport/jinair.png',
        departureTime: '20:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '03:00',
        arrivalAirport: '수완나품 국제공항',
        price: 574493,
        slug: 'lj3640-인천-방콕',
        baggage: '포함',
    },
    {
        id: 58,
        airline: '진에어',
        flightNo: 'LJ7936',
        logo: '/images/airport/jinair.png',
        departureTime: '00:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '07:45',
        arrivalAirport: '괌 국제공항',
        price: 249204,
        slug: 'lj7936-인천-괌',
        baggage: '포함',
    },
    {
        id: 59,
        airline: '진에어',
        flightNo: 'LJ2247',
        logo: '/images/airport/jinair.png',
        departureTime: '18:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간',
        direct: true,
        arrivalTime: '20:15',
        arrivalAirport: '창이 국제공항',
        price: 645202,
        slug: 'lj2247-인천-싱가포르',
        baggage: '미포함',
    },
    {
        id: 60,
        airline: '진에어',
        flightNo: 'LJ994',
        logo: '/images/airport/jinair.png',
        departureTime: '14:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '3시간 15분',
        direct: true,
        arrivalTime: '17:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 381538,
        slug: 'lj994-인천-나트랑',
        baggage: '포함',
    },
    {
        id: 61,
        airline: '진에어',
        flightNo: 'LJ7921',
        logo: '/images/airport/jinair.png',
        departureTime: '11:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '3시간 45분',
        direct: true,
        arrivalTime: '14:15',
        arrivalAirport: '다낭 국제공항',
        price: 184319,
        slug: 'lj7921-인천-다낭',
        baggage: '포함',
    },
    {
        id: 62,
        airline: '진에어',
        flightNo: 'LJ2153',
        logo: '/images/airport/jinair.png',
        departureTime: '03:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '3시간 30분',
        direct: true,
        arrivalTime: '06:30',
        arrivalAirport: '간사이 국제공항',
        price: 264079,
        slug: 'lj2153-인천-오사카',
        baggage: '포함',
    },
    {
        id: 63,
        airline: '진에어',
        flightNo: 'LJ8526',
        logo: '/images/airport/jinair.png',
        departureTime: '10:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '4시간',
        direct: true,
        arrivalTime: '14:15',
        arrivalAirport: '후쿠오카 국제공항',
        price: 327018,
        slug: 'lj8526-인천-후쿠오카',
        baggage: '미포함',
    },
    {
        id: 64,
        airline: '진에어',
        flightNo: 'LJ7139',
        logo: '/images/airport/jinair.png',
        departureTime: '03:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 45분',
        direct: true,
        arrivalTime: '09:00',
        arrivalAirport: '코타키나발루 국제공항',
        price: 162595,
        slug: 'lj7139-인천-코타키나발루',
        baggage: '포함',
    },
    {
        id: 65,
        airline: '진에어',
        flightNo: 'LJ980',
        logo: '/images/airport/jinair.png',
        departureTime: '03:30',
        departureAirport: '제주 국제공항',
        duration: '2시간',
        direct: true,
        arrivalTime: '05:30',
        arrivalAirport: '수완나품 국제공항',
        price: 238277,
        slug: 'lj980-제주-방콕',
        baggage: '포함',
    },
    {
        id: 66,
        airline: '진에어',
        flightNo: 'LJ4272',
        logo: '/images/airport/jinair.png',
        departureTime: '16:15',
        departureAirport: '제주 국제공항',
        duration: '7시간 45분',
        direct: true,
        arrivalTime: '23:00',
        arrivalAirport: '괌 국제공항',
        price: 427819,
        slug: 'lj4272-제주-괌',
        baggage: '포함',
    },
    {
        id: 67,
        airline: '진에어',
        flightNo: 'LJ9990',
        logo: '/images/airport/jinair.png',
        departureTime: '20:00',
        departureAirport: '제주 국제공항',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '02:15',
        arrivalAirport: '창이 국제공항',
        price: 205949,
        slug: 'lj9990-제주-싱가포르',
        baggage: '포함',
    },
    {
        id: 68,
        airline: '진에어',
        flightNo: 'LJ2165',
        logo: '/images/airport/jinair.png',
        departureTime: '07:45',
        departureAirport: '제주 국제공항',
        duration: '6시간',
        direct: true,
        arrivalTime: '13:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 310619,
        slug: 'lj2165-제주-나트랑',
        baggage: '포함',
    },
    {
        id: 69,
        airline: '진에어',
        flightNo: 'LJ5536',
        logo: '/images/airport/jinair.png',
        departureTime: '01:00',
        departureAirport: '제주 국제공항',
        duration: '7시간',
        direct: true,
        arrivalTime: '08:00',
        arrivalAirport: '다낭 국제공항',
        price: 231891,
        slug: 'lj5536-제주-다낭',
        baggage: '포함',
    },
    {
        id: 70,
        airline: '진에어',
        flightNo: 'LJ9518',
        logo: '/images/airport/jinair.png',
        departureTime: '21:15',
        departureAirport: '제주 국제공항',
        duration: '2시간',
        direct: true,
        arrivalTime: '23:15',
        arrivalAirport: '간사이 국제공항',
        price: 480712,
        slug: 'lj9518-제주-오사카',
        baggage: '포함',
    },
    {
        id: 71,
        airline: '진에어',
        flightNo: 'LJ3247',
        logo: '/images/airport/jinair.png',
        departureTime: '17:15',
        departureAirport: '제주 국제공항',
        duration: '7시간',
        direct: true,
        arrivalTime: '00:15',
        arrivalAirport: '후쿠오카 국제공항',
        price: 414462,
        slug: 'lj3247-제주-후쿠오카',
        baggage: '포함',
    },
    {
        id: 72,
        airline: '진에어',
        flightNo: 'LJ7531',
        logo: '/images/airport/jinair.png',
        departureTime: '16:15',
        departureAirport: '제주 국제공항',
        duration: '5시간',
        direct: true,
        arrivalTime: '21:15',
        arrivalAirport: '코타키나발루 국제공항',
        price: 626321,
        slug: 'lj7531-제주-코타키나발루',
        baggage: '포함',
    },
    {
        id: 73,
        airline: '제주항공',
        flightNo: '7C1466',
        logo: '/images/airport/jejuair.png',
        departureTime: '18:15',
        departureAirport: '김포 국제공항',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '23:30',
        arrivalAirport: '수완나품 국제공항',
        price: 397700,
        slug: '7c1466-김포-방콕',
        baggage: '포함',
    },
    {
        id: 74,
        airline: '제주항공',
        flightNo: '7C2345',
        logo: '/images/airport/jejuair.png',
        departureTime: '05:45',
        departureAirport: '김포 국제공항',
        duration: '4시간',
        direct: true,
        arrivalTime: '09:45',
        arrivalAirport: '괌 국제공항',
        price: 472674,
        slug: '7c2345-김포-괌',
        baggage: '미포함',
    },
    {
        id: 75,
        airline: '제주항공',
        flightNo: '7C3820',
        logo: '/images/airport/jejuair.png',
        departureTime: '00:15',
        departureAirport: '김포 국제공항',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '06:45',
        arrivalAirport: '창이 국제공항',
        price: 422904,
        slug: '7c3820-김포-싱가포르',
        baggage: '포함',
    },
    {
        id: 76,
        airline: '제주항공',
        flightNo: '7C5123',
        logo: '/images/airport/jejuair.png',
        departureTime: '17:15',
        departureAirport: '김포 국제공항',
        duration: '3시간',
        direct: true,
        arrivalTime: '20:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 376192,
        slug: '7c5123-김포-나트랑',
        baggage: '포함',
    },
    {
        id: 77,
        airline: '제주항공',
        flightNo: '7C4943',
        logo: '/images/airport/jejuair.png',
        departureTime: '21:45',
        departureAirport: '김포 국제공항',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '03:15',
        arrivalAirport: '다낭 국제공항',
        price: 610476,
        slug: '7c4943-김포-다낭',
        baggage: '포함',
    },
    {
        id: 78,
        airline: '제주항공',
        flightNo: '7C2006',
        logo: '/images/airport/jejuair.png',
        departureTime: '13:00',
        departureAirport: '김포 국제공항',
        duration: '3시간 15분',
        direct: true,
        arrivalTime: '16:15',
        arrivalAirport: '간사이 국제공항',
        price: 386394,
        slug: '7c2006-김포-오사카',
        baggage: '포함',
    },
    {
        id: 79,
        airline: '제주항공',
        flightNo: '7C2343',
        logo: '/images/airport/jejuair.png',
        departureTime: '19:45',
        departureAirport: '김포 국제공항',
        duration: '6시간',
        direct: true,
        arrivalTime: '01:45',
        arrivalAirport: '후쿠오카 국제공항',
        price: 470185,
        slug: '7c2343-김포-후쿠오카',
        baggage: '포함',
    },
    {
        id: 80,
        airline: '제주항공',
        flightNo: '7C3063',
        logo: '/images/airport/jejuair.png',
        departureTime: '01:15',
        departureAirport: '김포 국제공항',
        duration: '7시간 45분',
        direct: true,
        arrivalTime: '08:00',
        arrivalAirport: '코타키나발루 국제공항',
        price: 261287,
        slug: '7c3063-김포-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 81,
        airline: '제주항공',
        flightNo: '7C4586',
        logo: '/images/airport/jejuair.png',
        departureTime: '15:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간 30분',
        direct: true,
        arrivalTime: '17:30',
        arrivalAirport: '수완나품 국제공항',
        price: 450042,
        slug: '7c4586-인천-방콕',
        baggage: '포함',
    },
    {
        id: 82,
        airline: '제주항공',
        flightNo: '7C123',
        logo: '/images/airport/jejuair.png',
        departureTime: '02:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간 45분',
        direct: true,
        arrivalTime: '04:30',
        arrivalAirport: '괌 국제공항',
        price: 367543,
        slug: '7c123-인천-괌',
        baggage: '포함',
    },
    {
        id: 83,
        airline: '제주항공',
        flightNo: '7C3660',
        logo: '/images/airport/jejuair.png',
        departureTime: '10:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간',
        direct: true,
        arrivalTime: '15:15',
        arrivalAirport: '창이 국제공항',
        price: 150976,
        slug: '7c3660-인천-싱가포르',
        baggage: '미포함',
    },
    {
        id: 84,
        airline: '제주항공',
        flightNo: '7C2070',
        logo: '/images/airport/jejuair.png',
        departureTime: '17:45',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간 30분',
        direct: true,
        arrivalTime: '19:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 300137,
        slug: '7c2070-인천-나트랑',
        baggage: '포함',
    },
    {
        id: 85,
        airline: '제주항공',
        flightNo: '7C6818',
        logo: '/images/airport/jejuair.png',
        departureTime: '03:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '7시간',
        direct: true,
        arrivalTime: '10:00',
        arrivalAirport: '다낭 국제공항',
        price: 649021,
        slug: '7c6818-인천-다낭',
        baggage: '미포함',
    },
    {
        id: 86,
        airline: '제주항공',
        flightNo: '7C5583',
        logo: '/images/airport/jejuair.png',
        departureTime: '05:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 45분',
        direct: true,
        arrivalTime: '11:00',
        arrivalAirport: '간사이 국제공항',
        price: 505218,
        slug: '7c5583-인천-오사카',
        baggage: '포함',
    },
    {
        id: 87,
        airline: '제주항공',
        flightNo: '7C4294',
        logo: '/images/airport/jejuair.png',
        departureTime: '01:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '07:30',
        arrivalAirport: '후쿠오카 국제공항',
        price: 317735,
        slug: '7c4294-인천-후쿠오카',
        baggage: '포함',
    },
    {
        id: 88,
        airline: '제주항공',
        flightNo: '7C6951',
        logo: '/images/airport/jejuair.png',
        departureTime: '23:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '4시간 15분',
        direct: true,
        arrivalTime: '03:30',
        arrivalAirport: '코타키나발루 국제공항',
        price: 473335,
        slug: '7c6951-인천-코타키나발루',
        baggage: '포함',
    },
    {
        id: 89,
        airline: '제주항공',
        flightNo: '7C2407',
        logo: '/images/airport/jejuair.png',
        departureTime: '10:15',
        departureAirport: '제주 국제공항',
        duration: '2시간 30분',
        direct: true,
        arrivalTime: '12:45',
        arrivalAirport: '수완나품 국제공항',
        price: 335051,
        slug: '7c2407-제주-방콕',
        baggage: '미포함',
    },
    {
        id: 90,
        airline: '제주항공',
        flightNo: '7C6228',
        logo: '/images/airport/jejuair.png',
        departureTime: '21:30',
        departureAirport: '제주 국제공항',
        duration: '2시간',
        direct: true,
        arrivalTime: '23:30',
        arrivalAirport: '괌 국제공항',
        price: 226955,
        slug: '7c6228-제주-괌',
        baggage: '포함',
    },
    {
        id: 91,
        airline: '제주항공',
        flightNo: '7C3919',
        logo: '/images/airport/jejuair.png',
        departureTime: '18:30',
        departureAirport: '제주 국제공항',
        duration: '5시간 45분',
        direct: true,
        arrivalTime: '23:15',
        arrivalAirport: '창이 국제공항',
        price: 573576,
        slug: '7c3919-제주-싱가포르',
        baggage: '포함',
    },
    {
        id: 92,
        airline: '제주항공',
        flightNo: '7C5201',
        logo: '/images/airport/jejuair.png',
        departureTime: '17:15',
        departureAirport: '제주 국제공항',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '23:45',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 483102,
        slug: '7c5201-제주-나트랑',
        baggage: '미포함',
    },
    {
        id: 93,
        airline: '제주항공',
        flightNo: '7C3509',
        logo: '/images/airport/jejuair.png',
        departureTime: '07:15',
        departureAirport: '제주 국제공항',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '14:30',
        arrivalAirport: '다낭 국제공항',
        price: 351499,
        slug: '7c3509-제주-다낭',
        baggage: '포함',
    },
    {
        id: 94,
        airline: '제주항공',
        flightNo: '7C8478',
        logo: '/images/airport/jejuair.png',
        departureTime: '15:00',
        departureAirport: '제주 국제공항',
        duration: '7시간 15분',
        direct: true,
        arrivalTime: '22:15',
        arrivalAirport: '간사이 국제공항',
        price: 458406,
        slug: '7c8478-제주-오사카',
        baggage: '포함',
    },
    {
        id: 95,
        airline: '제주항공',
        flightNo: '7C1491',
        logo: '/images/airport/jejuair.png',
        departureTime: '05:30',
        departureAirport: '제주 국제공항',
        duration: '3시간 15분',
        direct: true,
        arrivalTime: '08:45',
        arrivalAirport: '후쿠오카 국제공항',
        price: 462038,
        slug: '7c1491-제주-후쿠오카',
        baggage: '미포함',
    },
    {
        id: 96,
        airline: '제주항공',
        flightNo: '7C5991',
        logo: '/images/airport/jejuair.png',
        departureTime: '12:15',
        departureAirport: '제주 국제공항',
        duration: '4시간 15분',
        direct: true,
        arrivalTime: '16:30',
        arrivalAirport: '코타키나발루 국제공항',
        price: 393787,
        slug: '7c5991-제주-코타키나발루',
        baggage: '포함',
    },
    {
        id: 97,
        airline: '티웨이항공',
        flightNo: 'TW2445',
        logo: '/images/airport/tway.png',
        departureTime: '00:45',
        departureAirport: '김포 국제공항',
        duration: '7시간 45분',
        direct: true,
        arrivalTime: '07:30',
        arrivalAirport: '수완나품 국제공항',
        price: 300463,
        slug: 'tw2445-김포-방콕',
        baggage: '미포함',
    },
    {
        id: 98,
        airline: '티웨이항공',
        flightNo: 'TW5217',
        logo: '/images/airport/tway.png',
        departureTime: '17:15',
        departureAirport: '김포 국제공항',
        duration: '6시간 30분',
        direct: true,
        arrivalTime: '23:45',
        arrivalAirport: '괌 국제공항',
        price: 613857,
        slug: 'tw5217-김포-괌',
        baggage: '포함',
    },
    {
        id: 99,
        airline: '티웨이항공',
        flightNo: 'TW5404',
        logo: '/images/airport/tway.png',
        departureTime: '21:00',
        departureAirport: '김포 국제공항',
        duration: '4시간',
        direct: true,
        arrivalTime: '01:00',
        arrivalAirport: '창이 국제공항',
        price: 534170,
        slug: 'tw5404-김포-싱가포르',
        baggage: '미포함',
    },
    {
        id: 100,
        airline: '티웨이항공',
        flightNo: 'TW258',
        logo: '/images/airport/tway.png',
        departureTime: '07:30',
        departureAirport: '김포 국제공항',
        duration: '7시간 45분',
        direct: true,
        arrivalTime: '14:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 524076,
        slug: 'tw258-김포-나트랑',
        baggage: '포함',
    },
    {
        id: 101,
        airline: '티웨이항공',
        flightNo: 'TW5840',
        logo: '/images/airport/tway.png',
        departureTime: '13:00',
        departureAirport: '김포 국제공항',
        duration: '5시간 30분',
        direct: true,
        arrivalTime: '18:30',
        arrivalAirport: '다낭 국제공항',
        price: 239082,
        slug: 'tw5840-김포-다낭',
        baggage: '포함',
    },
    {
        id: 102,
        airline: '티웨이항공',
        flightNo: 'TW2924',
        logo: '/images/airport/tway.png',
        departureTime: '12:15',
        departureAirport: '김포 국제공항',
        duration: '3시간 30분',
        direct: true,
        arrivalTime: '15:45',
        arrivalAirport: '간사이 국제공항',
        price: 166944,
        slug: 'tw2924-김포-오사카',
        baggage: '포함',
    },
    {
        id: 103,
        airline: '티웨이항공',
        flightNo: 'TW3887',
        logo: '/images/airport/tway.png',
        departureTime: '03:30',
        departureAirport: '김포 국제공항',
        duration: '6시간 15분',
        direct: true,
        arrivalTime: '09:45',
        arrivalAirport: '후쿠오카 국제공항',
        price: 154389,
        slug: 'tw3887-김포-후쿠오카',
        baggage: '미포함',
    },
    {
        id: 104,
        airline: '티웨이항공',
        flightNo: 'TW6138',
        logo: '/images/airport/tway.png',
        departureTime: '04:30',
        departureAirport: '김포 국제공항',
        duration: '5시간',
        direct: true,
        arrivalTime: '09:30',
        arrivalAirport: '코타키나발루 국제공항',
        price: 251811,
        slug: 'tw6138-김포-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 105,
        airline: '티웨이항공',
        flightNo: 'TW1475',
        logo: '/images/airport/tway.png',
        departureTime: '11:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간 30분',
        direct: true,
        arrivalTime: '13:30',
        arrivalAirport: '수완나품 국제공항',
        price: 480389,
        slug: 'tw1475-인천-방콕',
        baggage: '미포함',
    },
    {
        id: 106,
        airline: '티웨이항공',
        flightNo: 'TW1282',
        logo: '/images/airport/tway.png',
        departureTime: '16:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 45분',
        direct: true,
        arrivalTime: '22:00',
        arrivalAirport: '괌 국제공항',
        price: 356461,
        slug: 'tw1282-인천-괌',
        baggage: '포함',
    },
    {
        id: 107,
        airline: '티웨이항공',
        flightNo: 'TW2329',
        logo: '/images/airport/tway.png',
        departureTime: '17:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간 15분',
        direct: true,
        arrivalTime: '22:30',
        arrivalAirport: '창이 국제공항',
        price: 162388,
        slug: 'tw2329-인천-싱가포르',
        baggage: '미포함',
    },
    {
        id: 108,
        airline: '티웨이항공',
        flightNo: 'TW7505',
        logo: '/images/airport/tway.png',
        departureTime: '11:30',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '6시간 45분',
        direct: true,
        arrivalTime: '17:15',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 349044,
        slug: 'tw7505-인천-나트랑',
        baggage: '포함',
    },
    {
        id: 109,
        airline: '티웨이항공',
        flightNo: 'TW4827',
        logo: '/images/airport/tway.png',
        departureTime: '03:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '2시간 30분',
        direct: true,
        arrivalTime: '05:30',
        arrivalAirport: '다낭 국제공항',
        price: 547889,
        slug: 'tw4827-인천-다낭',
        baggage: '미포함',
    },
    {
        id: 110,
        airline: '티웨이항공',
        flightNo: 'TW9498',
        logo: '/images/airport/tway.png',
        departureTime: '17:00',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '4시간 15분',
        direct: true,
        arrivalTime: '21:15',
        arrivalAirport: '간사이 국제공항',
        price: 157840,
        slug: 'tw9498-인천-오사카',
        baggage: '포함',
    },
    {
        id: 111,
        airline: '티웨이항공',
        flightNo: 'TW7326',
        logo: '/images/airport/tway.png',
        departureTime: '12:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간 45분',
        direct: true,
        arrivalTime: '17:00',
        arrivalAirport: '후쿠오카 국제공항',
        price: 493464,
        slug: 'tw7326-인천-후쿠오카',
        baggage: '포함',
    },
    {
        id: 112,
        airline: '티웨이항공',
        flightNo: 'TW8755',
        logo: '/images/airport/tway.png',
        departureTime: '07:15',
        departureAirport: '인천 국제공항 - 터미널 2',
        duration: '5시간',
        direct: true,
        arrivalTime: '12:15',
        arrivalAirport: '코타키나발루 국제공항',
        price: 542427,
        slug: 'tw8755-인천-코타키나발루',
        baggage: '미포함',
    },
    {
        id: 113,
        airline: '티웨이항공',
        flightNo: 'TW4532',
        logo: '/images/airport/tway.png',
        departureTime: '04:00',
        departureAirport: '제주 국제공항',
        duration: '6시간',
        direct: true,
        arrivalTime: '10:00',
        arrivalAirport: '수완나품 국제공항',
        price: 294788,
        slug: 'tw4532-제주-방콕',
        baggage: '포함',
    },
    {
        id: 114,
        airline: '티웨이항공',
        flightNo: 'TW6072',
        logo: '/images/airport/tway.png',
        departureTime: '20:15',
        departureAirport: '제주 국제공항',
        duration: '2시간 45분',
        direct: true,
        arrivalTime: '22:00',
        arrivalAirport: '괌 국제공항',
        price: 508573,
        slug: 'tw6072-제주-괌',
        baggage: '포함',
    },
    {
        id: 115,
        airline: '티웨이항공',
        flightNo: 'TW6694',
        logo: '/images/airport/tway.png',
        departureTime: '03:30',
        departureAirport: '제주 국제공항',
        duration: '2시간',
        direct: true,
        arrivalTime: '05:30',
        arrivalAirport: '창이 국제공항',
        price: 605783,
        slug: 'tw6694-제주-싱가포르',
        baggage: '포함',
    },
    {
        id: 116,
        airline: '티웨이항공',
        flightNo: 'TW4204',
        logo: '/images/airport/tway.png',
        departureTime: '19:30',
        departureAirport: '제주 국제공항',
        duration: '7시간 30분',
        direct: true,
        arrivalTime: '02:00',
        arrivalAirport: '나트랑 깜라인 국제공항',
        price: 518764,
        slug: 'tw4204-제주-나트랑',
        baggage: '포함',
    },
    {
        id: 117,
        airline: '티웨이항공',
        flightNo: 'TW2836',
        logo: '/images/airport/tway.png',
        departureTime: '18:00',
        departureAirport: '제주 국제공항',
        duration: '3시간 45분',
        direct: true,
        arrivalTime: '21:45',
        arrivalAirport: '다낭 국제공항',
        price: 377930,
        slug: 'tw2836-제주-다낭',
        baggage: '미포함',
    },
    {
        id: 118,
        airline: '티웨이항공',
        flightNo: 'TW5819',
        logo: '/images/airport/tway.png',
        departureTime: '01:15',
        departureAirport: '제주 국제공항',
        duration: '7시간 30분',
        direct: true,
        arrivalTime: '08:45',
        arrivalAirport: '간사이 국제공항',
        price: 592899,
        slug: 'tw5819-제주-오사카',
        baggage: '미포함',
    },
    {
        id: 119,
        airline: '티웨이항공',
        flightNo: 'TW9507',
        logo: '/images/airport/tway.png',
        departureTime: '07:45',
        departureAirport: '제주 국제공항',
        duration: '7시간',
        direct: true,
        arrivalTime: '14:45',
        arrivalAirport: '후쿠오카 국제공항',
        price: 306602,
        slug: 'tw9507-제주-후쿠오카',
        baggage: '포함',
    },
    {
        id: 120,
        airline: '티웨이항공',
        flightNo: 'TW8921',
        logo: '/images/airport/tway.png',
        departureTime: '19:15',
        departureAirport: '제주 국제공항',
        duration: '2시간 30분',
        direct: true,
        arrivalTime: '21:45',
        arrivalAirport: '코타키나발루 국제공항',
        price: 509664,
        slug: 'tw8921-제주-코타키나발루',
        baggage: '미포함',
    },
];
