export default [
    {
        id: 1,
        name: '그랜드 하얏트 제주',
        engName: 'Grand Hyatt Jeju',
        slug: 'grand-hyatt-jeju',
        type: '호텔', // hotel/resort, pension, guesthouse, hanok, villa, capsule, etc
        star: '3성급', // 성급
        location: '제주 제주시',
        price: 326480,
        rate: 4.8,
        reviewCount: 25, // 개수 세는 함수..?
        about: '제주도의 중심에 위치한 그랜드 하얏트 제주는 럭셔리한 분위기와 최고급 편의시설로 모두에게 특별한 경험을 선사하는 호텔입니다. 한라산과 제주 바다를 한눈에 담을 수 있는 객실과 국내 최대 규모의 복합 리조트 내 다양한 다이닝 시설, 실내외 수영장을 갖추고 있으며, 공항과 가까워 편리한 제주 여행을 즐길 수 있습니다.', // 숙소 설명
        phone: '064-907-1234',
        mail: 'jeju.grand@hyatt.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ], // 숙소 정책 - 숙소 타입별로 다르게?
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ], // 취소 정책 - 숙소 타입별로 다르게?
        address: '제주특별자치도 서귀포시 중문관광로 116',
        landmark: ['제주국제공항 차량 10분', '동문시장 차량 15분', '한라수목원 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '레스토랑',
            '반려동물 동반',
            '주차',
            '24시간 체크인',
            '스파',
            '개별 바베큐',
        ],
        image: ['ht-1-a.jpg', 'ht-1-b.jpg'],
        // 박 수, 인원은 검색창에서 데이터 받아와야함
        // 이 배열?안에 리뷰 데이터도 있어야 아니다 리뷰 데이터는 따로 관리하고 id로 연결
        // 객실 선택 데이터 따로 만들기 - 숙소 타입별로 분류?
    },
    {
        id: 2,
        name: '세인트존스 호텔',
        engName: 'Saint Johns Hotel',
        slug: 'saint-johns-hotel',
        type: '호텔',
        star: '5성급',
        location: '서울 중구',
        price: 310000, // 임시
        rate: 4.6,
        reviewCount: null,
        about: '서울 중심부에 위치한 롯데호텔 서울은 비즈니스와 관광객 모두에게 적합한 프리미엄 호텔입니다. 고급스러운 인테리어와 다양한 다이닝 옵션, 대형 연회장을 갖추고 있어 국제적인 행사와 숙박에 자주 이용됩니다. 지하철과 연결되어 교통 접근성이 뛰어납니다.',
        phone: '02-771-1000',
        mail: 'reservation@lottehotel.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '강원특별자치도 강릉시 창해로 307',
        landmark: ['명동 도보 5분', '서울광장 도보 3분', '덕수궁 차량 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '스파',
            '개별 바베큐',
        ],
        image: ['ht-2-a.webp', 'ht-2-b.webp'],
    },
    {
        id: 3,
        name: '파라다이스 호텔 부산',
        engName: 'Paradise Hotel Busan',
        slug: 'paradise-hotel-busan',
        type: '호텔',
        star: '5성급',
        location: '부산 해운대구',
        price: 270000, // 임시
        rate: 4.8,
        reviewCount: null,
        about: '부산 해운대 해수욕장 앞에 위치한 파라다이스 호텔 부산은 탁 트인 바다 전망과 고급스러운 서비스로 유명합니다. 야외 온천 스파와 인피니티 풀을 갖추고 있으며, 연인과 가족 여행객에게 모두 인기 있는 리조트형 호텔입니다. 해변 접근성이 뛰어나 휴양에 최적입니다.',
        phone: '051-742-2121',
        mail: 'info@paradisehotel.co.kr',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '부산광역시 해운대구 해운대해변로 296',
        landmark: ['해운대해수욕장 도보 1분', '동백섬 차량 5분', '부산 아쿠아리움 도보 3분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '반려동물 동반',
            '주차',
            '스파',
            '개별 바베큐',
        ],
        image: ['ht-3-a.webp', 'ht-3-b.webp'],
    },
    {
        id: 4,
        name: '웨스틴 조선 부산',
        engName: 'Westin Josun Busan',
        slug: 'westin-josun-busan',
        type: '호텔',
        star: '5성급',
        location: '부산 해운대구',
        price: 250000, // 임시
        rate: 4.5,
        reviewCount: null,
        about: '해운대 동백섬 옆에 위치한 웨스틴 조선 부산은 고급스러운 분위기와 편안한 서비스로 오랫동안 사랑받아온 호텔입니다. 바다 전망 객실과 다양한 다이닝 시설, 피트니스 클럽을 제공하며, 해운대 해변을 바로 연결해 편리한 휴가를 즐길 수 있습니다.',
        phone: '051-749-7000',
        mail: 'info@westinbusan.co.kr',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '부산광역시 해운대구 동백로 67',
        landmark: ['동백섬 도보 2분', '누리마루 APEC하우스 도보 5분', '해운대해수욕장 도보 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '반려동물 동반',
            '주차',
            '24시간 체크인',
        ],
        image: ['ht-4-a.webp', 'ht-4-b.webp'],
    },
    {
        id: 5,
        name: '켄싱턴호텔 평창',
        engName: 'Kensington Hotel Pyeongchang',
        slug: 'kensington-hotel-pyeongchang',
        type: '호텔',
        star: '4성급',
        location: '강원 평창군',
        price: 180000, // 임시
        rate: 4.4,
        reviewCount: null,
        about: '강원도 대관령의 자연 속에 위치한 켄싱턴호텔 평창은 가족 단위 여행객에게 인기 있는 리조트형 호텔입니다. 사계절 내내 다양한 액티비티를 즐길 수 있으며, 깨끗한 공기와 함께 휴식을 취할 수 있습니다. 특히 겨울철 스키 여행객들에게 적합합니다.',
        phone: '033-335-5000',
        mail: 'info@kensington.co.kr',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '강원특별자치도 평창군 진부면 진고개로 231',
        landmark: [
            '알펜시아 스키장 차량 10분',
            '용평리조트 차량 15분',
            '대관령 양떼목장 차량 12분',
        ],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-5-a.webp', 'ht-5-b.webp'],
    },
    {
        id: 6,
        name: '롯데리조트 속초',
        engName: 'Lotte Resort Sokcho',
        slug: 'lotte-resort-sokcho',
        type: '호텔',
        star: '4성급',
        location: '강원 속초시',
        price: 200000, // 임시
        rate: 4.6,
        reviewCount: null,
        about: '동해 바다와 설악산 전망을 동시에 즐길 수 있는 롯데리조트 속초는 가족 단위 여행객에게 사랑받는 숙소입니다. 객실마다 바다 전망을 제공하며, 인피니티 풀과 키즈 전용 공간도 마련되어 있어 휴양과 여가를 함께 즐기기에 좋습니다.',
        phone: '033-634-1000',
        mail: 'info@lotteresort.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '강원특별자치도 속초시 대포동 대포항길 186',
        landmark: [
            '속초해수욕장 차량 5분',
            '설악산 국립공원 차량 15분',
            '청초호 호수공원 차량 7분',
        ],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '레스토랑',
            '반려동물 동반',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-6-a.webp', 'ht-6-b.webp'],
    },
    {
        id: 7,
        name: '힐튼 경주',
        engName: 'Hilton Gyeongju',
        slug: 'hilton-gyeongju',
        type: '호텔',
        star: '5성급',
        location: '경북 경주시',
        price: 240000, // 임시
        rate: 4.5,
        reviewCount: null,
        about: '보문호수 옆에 위치한 힐튼 경주는 경주의 대표적인 럭셔리 호텔입니다. 고급스러운 객실과 다양한 편의시설을 갖추고 있으며, 가족 여행과 비즈니스 행사에 모두 적합합니다. 역사 도시 경주의 주요 관광지와 인접해 있어 문화 탐방에도 유리합니다.',
        phone: '054-745-7788',
        mail: 'reservation@hilton.co.kr',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '경상북도 경주시 보덕동 보문로 484-7',
        landmark: ['보문호 도보 5분', '불국사 차량 15분', '경주월드 차량 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '주차',
            '24시간 체크인',
            '스파',
            '개별 바베큐',
        ],
        image: ['ht-7-a.webp', 'ht-7-b.webp'],
    },
    {
        id: 8,
        name: '라마다 프라자 제주호텔',
        engName: 'Ramada Plaza Jeju Hotel',
        slug: 'ramada-plaza-jeju',
        type: '호텔',
        star: '5성급',
        location: '제주시 제주',
        price: 210000, // 임시
        rate: 4.4,
        reviewCount: null,
        about: '제주 바닷가 바로 앞에 위치한 라마다 프라자 제주호텔은 이국적인 분위기와 함께 다양한 편의시설을 제공합니다. 국제공항과 가까워 접근성이 좋으며, 비즈니스와 관광객 모두에게 적합한 숙소입니다.',
        phone: '064-729-8100',
        mail: 'reservation@ramadajeju.co.kr',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '제주특별자치도 제주시 탑동로 66',
        landmark: ['용두암 차량 5분', '동문시장 차량 10분', '제주국제공항 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-8-a.webp', 'ht-8-b.webp'],
    },
    {
        id: 9,
        name: '노보텔 앰배서더 수원',
        engName: 'Novotel Ambassador Suwon',
        slug: 'novotel-ambassador-suwon',
        type: '호텔',
        star: '4성급',
        location: '경기 수원시',
        price: 200000,
        rate: 4.4,
        reviewCount: null,
        about: '수원역 바로 앞에 위치한 국제 체인 4성급 호텔로 교통과 레스토랑 접근성이 좋고, 비즈니스 및 관광에 적합합니다.',
        phone: '031-230-6600',
        mail: 'reservation@novotelsuwon.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '경기도 수원시 팔달구 권광로180번길 53-22', // “HOTEL 여기어때 - 수원정자점” 정보에서 주소 참고 :contentReference[oaicite:0]{index=0}
        landmark: ['수원역 도보 5분', '화성행궁 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '수화물 보관',
            '스파',
        ],
        image: ['ht-9-a.webp', 'ht-9-b.webp'],
    },
    {
        id: 10,
        name: '전주 라한호텔',
        engName: 'Rahan Hotel Jeonju',
        slug: 'rahan-hotel-jeonju',
        type: '호텔',
        star: '4성급',
        location: '전북 전주시',
        price: 150000, // 임시
        rate: 4.3,
        reviewCount: null,
        about: '전주 한옥마을 인근에 위치한 라한호텔은 전통과 현대가 조화를 이룬 호텔입니다. 전통문화를 체험하면서도 편리한 현대식 시설을 이용할 수 있어 관광객들에게 인기 있는 숙소입니다.',
        phone: '063-720-7000',
        mail: 'info@rahanhotel.co.kr',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '전북특별자치도 전주시 완산구 기린대로 85',
        landmark: ['중문 색달해변 차량 5분', '천제연 폭포 차량 7분', '여미지 식물원 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '반려동물 동반',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-10-a.webp', 'ht-10-b.webp'],
    },
    {
        id: 11,
        name: '라마다 프라자 수원 호텔',
        engName: 'Ramada Plaza Suwon Hotel',
        slug: 'ramada-plaza-suwon-hotel',
        type: '호텔',
        star: '4성급',
        location: '경기 수원시',
        price: 220000,
        rate: 4.3,
        reviewCount: null,
        about: '수원 중심부에 위치한 고급 중형 호텔로서, 비즈니스, 쇼핑, 여가를 위해 이용하기 좋은 옵션입니다.',
        phone: '031-230-0001',
        mail: 'info@ramadaplazasuwon.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '경기도 수원시 팔달구 중부대로 150',
        landmark: ['수원역 차량 5분', '화성행궁 차량 8분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '수화물 보관',
            '스파',
            '반려동물 동반',
        ],
        image: ['ht-11-a.webp', 'ht-11-b.webp'],
    },
    {
        id: 12,
        name: '유탑 마리나 호텔 & 리조트 여수 엑스포',
        engName: 'Utour Marina Hotel & Resort Yeosu Expo',
        slug: 'utop-marina-yeosu-expo',
        type: '호텔',
        star: '5성급',
        location: '전남 여수시',
        price: 250000,
        rate: 4.5,
        reviewCount: null,
        about: '엑스포 해양공원 인근에 위치한 리조트형 호텔로, 바다 전망과 다양한 레저 시설이 제공됩니다.',
        phone: '061-663-0100',
        mail: 'reservations@utopmarina.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '전라남도 여수시 박람회길 10',
        landmark: ['엑스포해양공원 도보 2분', '돌산대교 차량 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '수화물 보관',
            '스파',
            '반려동물 동반',
        ],
        image: ['ht-12-a.webp', 'ht-12-b.webp'],
    },
    {
        id: 13,
        name: '신라 스테이 여수 엑스포역',
        engName: 'Shilla Stay Yeosu Expo',
        slug: 'shilla-stay-yeosu-expo',
        type: '호텔',
        star: '4성급',
        location: '전남 여수시',
        price: 150000,
        rate: 4.2,
        reviewCount: null,
        about: '여수 엑스포역 인근에 위치한 실속형 호텔로, 교통편이 좋고 관광 명소 접근이 편리합니다.',
        phone: '061-660-4000',
        mail: 'expo@shillastay.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '전라남도 여수시 박람회길 1',
        landmark: ['여수 엑스포역 도보 3분', '이순신광장 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '수화물 보관',
            '반려동물 동반',
        ],
        image: ['ht-13-a.webp', 'ht-13-b.webp'],
    },
    {
        id: 14,
        name: '호텔 선샤인 대전',
        engName: 'Hotel Sunshine Daejeon',
        slug: 'hotel-sunshine-daejeon',
        type: '호텔',
        star: '4성급',
        location: '대전 유성구',
        price: 140000, // 임시
        rate: 4.1,
        reviewCount: null,
        about: '대전 유성 온천 지구에 위치한 호텔 선샤인은 깔끔하고 합리적인 가격대의 숙소입니다. 온천과 가까워 휴양을 즐기기에 좋으며, 인근에 다양한 레스토랑과 관광지가 있어 가족 여행객들에게 인기가 있습니다.',
        phone: '042-823-7001',
        mail: 'info@sunshinedaejeon.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '대전광역시 동구 가양동 451-1',
        landmark: ['유성온천 도보 5분', '대전엑스포과학공원 차량 10분', '한밭수목원 차량 15분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-14-a.webp', 'ht-14-b.webp'],
    },
    {
        id: 15,
        name: '베스트웨스턴 전주 호텔',
        engName: 'Best Western Jeonju Hotel',
        slug: 'best-western-jeonju',
        type: '호텔',
        star: '4성급',
        location: '전북 전주시',
        price: 130000, // 임시
        rate: 4.2,
        reviewCount: null,
        about: '전주 한옥마을과 가까운 위치에 자리한 베스트웨스턴 전주 호텔은 깔끔한 시설과 합리적인 가격으로 관광객에게 인기 있는 호텔입니다. 전통과 현대가 공존하는 전주 여행의 거점으로 좋은 선택입니다.',
        phone: '063-720-9000',
        mail: 'info@bestwesternjeonju.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '전북특별자치도 전주시 완산구 현무1길 41',
        landmark: ['전주 한옥마을 도보 10분', '경기전 차량 7분', '덕진공원 차량 12분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '레스토랑',
            '반려동물 동반',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-15-a.webp', 'ht-15-b.webp'],
    },
    {
        id: 16,
        name: '만다린 오리엔탈 방콕',
        engName: 'Mandarin Oriental Bangkok',
        slug: 'mandarin-oriental-bangkok',
        type: '호텔',
        star: '5성급',
        location: '태국 방콕',
        price: 480000,
        rate: 4.8,
        reviewCount: null,
        about: '차오프라야 강변에 위치한 방콕의 대표 럭셔리 호텔로, 전통과 현대가 어우러진 우아한 분위기를 자랑합니다.',
        phone: '+66 2 659 9000',
        mail: 'mobkk-reservations@mohg.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '48 Oriental Avenue, Bang Rak, Bangkok 10500 Thailand',
        landmark: ['사톤 부두 도보 5분', '아이콘시암 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '주차',
            '스파',
            '24시간 체크인',
            '수화물 보관',
            '반려동물 동반',
        ],
        image: ['ht-16-a.webp', 'ht-16-b.webp'],
    },
    {
        id: 17,
        name: '샹그릴라 호텔 방콕',
        engName: 'Shangri-La Bangkok',
        slug: 'shangri-la-bangkok',
        type: '호텔',
        star: '5성급',
        location: '태국 방콕',
        price: 360000,
        rate: 4.7,
        reviewCount: null,
        about: '차오프라야 강변의 대표적인 5성급 호텔로, 넓은 수영장과 다양한 레스토랑을 보유하고 있습니다.',
        phone: '+66 2 236 7777',
        mail: 'slbk@shangri-la.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '89 Soi Wat Suan Plu, New Road, Bangrak, Bangkok 10500 Thailand',
        landmark: ['사판탁신 BTS역 도보 5분', '아이콘시암 차량 7분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '스파',
        ],
        image: ['ht-17-a.webp', 'ht-17-b.webp'],
    },
    {
        id: 18,
        name: '두짓 비치 리조트 괌',
        engName: 'Dusit Beach Resort Guam',
        slug: 'dusit-beach-resort-guam',
        type: '호텔',
        star: '5성급',
        location: '괌 투몬',
        price: 420000,
        rate: 4.5,
        reviewCount: null,
        about: '투몬 비치 바로 앞에 위치한 럭셔리 리조트로, 가족 여행객에게 인기 있는 숙소입니다.',
        phone: '+1 671-649-8815',
        mail: 'reservations@dusit.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '1255 Pale San Vitores Rd, Tumon, Guam 96913',
        landmark: ['투몬 비치 도보 1분', '괌 프리미엄 아울렛 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '스파',
            '주차',
            '24시간 체크인',
            '수화물 보관',
        ],
        image: ['ht-18-a.webp', 'ht-18-b.webp'],
    },
    {
        id: 19,
        name: '롯데 호텔 괌',
        engName: 'Lotte Hotel Guam',
        slug: 'lotte-hotel-guam',
        type: '호텔',
        star: '5성급',
        location: '괌 투몬',
        price: 350000,
        rate: 4.4,
        reviewCount: null,
        about: '투몬 베이에 위치한 한국계 럭셔리 호텔로, 탁 트인 오션뷰와 가족 친화적인 시설이 특징입니다.',
        phone: '+1 671-646-6811',
        mail: 'rsvn@lottehotelguam.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '185 Gun Beach Rd, Tumon, Guam 96913',
        landmark: ['건비치 도보 3분', '투몬 샌드플라자 차량 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '반려동물 동반',
            '주차',
            '24시간 체크인',
            '스파',
            '수화물 보관',
        ],
        image: ['ht-19-a.webp', 'ht-19-b.webp'],
    },
    {
        id: 20,
        name: '마리나 베이 샌즈',
        engName: 'Marina Bay Sands Singapore',
        slug: 'marina-bay-sands',
        type: '호텔',
        star: '5성급',
        location: '싱가포르',
        price: 550000,
        rate: 4.7,
        reviewCount: null,
        about: '싱가포르의 랜드마크 호텔로, 인피니티 풀과 스카이파크 전망대가 유명합니다.',
        phone: '+65 6688 8868',
        mail: 'reservations@marinabaysands.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '10 Bayfront Avenue, Singapore 018956',
        landmark: ['가든스 바이 더 베이 도보 5분', '멀라이언 파크 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '스파',
            '피트니스',
            '주차',
            '24시간 체크인',
            '수화물 보관',
        ],
        image: ['ht-20-a.webp', 'ht-20-b.webp'],
    },
    {
        id: 21,
        name: '래플스 호텔 싱가포르',
        engName: 'Raffles Hotel Singapore',
        slug: 'raffles-hotel-singapore',
        type: '호텔',
        star: '5성급',
        location: '싱가포르',
        price: 600000,
        rate: 4.9,
        reviewCount: null,
        about: '1887년에 문을 연 싱가포르의 대표적인 유서 깊은 럭셔리 호텔로, 전통과 현대가 조화를 이루고 있습니다.',
        phone: '+65 6337 1886',
        mail: 'reservations@raffles.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '1 Beach Road, Singapore 189673',
        landmark: ['시티홀 MRT역 도보 2분', '오차드로드 차량 8분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수화물 보관',
            '레스토랑',
            '스파',
            '주차',
            '24시간 체크인',
            '수영장',
        ],
        image: ['ht-21-a.webp', 'ht-21-b.webp'],
    },
    {
        id: 22,
        name: 'InterContinental Nha Trang',
        engName: 'InterContinental Nha Trang',
        slug: 'intercontinental-nha-trang',
        type: '호텔',
        star: '5성급',
        location: '베트남 나트랑',
        price: 300000,
        rate: 4.6,
        reviewCount: null,
        about: 'Tran Phu 해변에 위치한 럭셔리 호텔로 다양한 레스토랑과 스파, 전용 해변을 갖추고 있습니다.',
        phone: '+84 258 3525 555',
        mail: 'info@intercontinental-nhatrang.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '32–34 Tran Phu, Nha Trang, Khánh Hòa, Vietnam', // 공개 정보 :contentReference[oaicite:0]{index=0}
        landmark: ['Tran Phu 해변 도보 1분', 'Po Nagar Cham Towers 차량 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '스파',
            '주차',
            '24시간 체크인',
            '수화물 보관',
            '반려동물 동반',
        ],
        image: ['ht-22-a.webp', 'ht-22-b.webp'],
    },
    {
        id: 23,
        name: 'Sheraton Nha Trang Hotel & Spa',
        engName: 'Sheraton Nha Trang Hotel & Spa',
        slug: 'sheraton-nha-trang-hotel-spa',
        type: '호텔',
        star: '5성급',
        location: '베트남 나트랑',
        price: 280000,
        rate: 4.5,
        reviewCount: null,
        about: '바다 전망의 인피니티 풀과 키즈 클럽, 풀사이드 다이닝이 특징인 가족 여행에 적합한 호텔입니다.',
        phone: '+84 258 3524 333',
        mail: 'reservations@sheratonnhatrang.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '10 Tran Phu, Nha Trang, Khánh Hòa, Vietnam', // 공개 정보 :contentReference[oaicite:1]{index=1}
        landmark: ['Tran Phu 해변 도보 2분', '밤 시장 차량 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '스파',
            '24시간 체크인',
            '주차',
            '수화물 보관',
        ],
        image: ['ht-23-a.webp', 'ht-23-b.webp'],
    },
    {
        id: 24,
        name: '코타키나발루 메리어트 호텔',
        engName: 'Kota Kinabalu Marriott Hotel',
        slug: 'kota-kinabalu-marriott-hotel',
        type: '호텔',
        star: '5성급',
        location: '말레이시아 코타키나발루',
        price: 330000,
        rate: 4.4,
        reviewCount: null,
        about: 'South China Sea 옆에 위치한 현대적이고 고급스러운 호텔로, 바다 전망 객실과 다양한 레스토랑을 보유하고 있습니다.',
        phone: '+60 88-286 888',
        mail: 'reservations@marriottkk.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: 'Lot G-23A, Jalan Tun Fuad Stephens, 88000 Kota Kinabalu, Sabah, Malaysia', // 공개 정보 :contentReference[oaicite:2]{index=2}
        landmark: ['워터프론트 인근', '필리피노 마켓 도보 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '주차',
            '24시간 체크인',
            '수화물 보관',
            '스파',
        ],
        image: ['ht-24-a.webp', 'ht-24-b.webp'],
    },
    {
        id: 25,
        name: '힐튼 코타키나발루',
        engName: 'Hilton Kota Kinabalu',
        slug: 'hilton-kota-kinabalu',
        type: '호텔',
        star: '5성급',
        location: '말레이시아 코타키나발루',
        price: 320000,
        rate: 4.5,
        reviewCount: null,
        about: '도심 중심부에 자리잡은 Hilton 호텔로, 루프탑 풀과 바, 바다 또는 시티뷰 객실을 제공합니다.',
        phone: '+60 88-515 888',
        mail: 'info@hiltonkk.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: 'Jalan Tun Fuad Stephens, Kota Kinabalu, Sabah, Malaysia', // 근접 정보 :contentReference[oaicite:3]{index=3}
        landmark: ['제셀튼 제티 차량 5분', '워터프론트 쇼핑몰 도보 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '24시간 체크인',
            '수화물 보관',
            '주차',
            '스파',
            '반려동물 동반',
        ],
        image: ['ht-25-a.jpg', 'ht-25-b.jpg'],
    },
    {
        id: 26,
        name: '호텔 니코 오사카',
        engName: 'Hotel Nikko Osaka',
        slug: 'hotel-nikko-osaka',
        type: '호텔',
        star: '5성급',
        location: '일본 오사카',
        price: 280000,
        rate: 4.4,
        reviewCount: null,
        about: '난바 지역 중심부에 위치한 고급 호텔로, 쇼핑과 먹거리 탐방에 매우 좋습니다.',
        phone: '+81 6-6244-1111',
        mail: 'reservation@hotelnikko-osaka.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '1-3-3 Nishi-Shinsaibashi, Chuo-ku, Osaka 542-0086, Japan',
        landmark: ['도톤보리 도보 5분', '신사이바시 쇼핑 거리 도보 3분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '24시간 체크인',
            '주차',
            '수화물 보관',
            '스파',
        ],
        image: ['ht-26-a.webp', 'ht-26-b.webp'],
    },
    {
        id: 27,
        name: '호텔 몬테레이 그라치아 오사카',
        engName: 'Hotel Monterey Grasmere Osaka',
        slug: 'hotel-monterey-grasmere-osaka',
        type: '호텔',
        star: '4성급',
        location: '일본 오사카',
        price: 230000,
        rate: 4.3,
        reviewCount: null,
        about: '우메다 지역에 위치한 클래식 스타일의 호텔로, 도심 이동이 편리합니다.',
        phone: '+81 6-6347-8555',
        mail: 'info@hotelmonterey.co.jp',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '1-2-3 Minami-Motomachi, Chuo-ku, Osaka 540-0004, Japan',
        landmark: ['우메다 역 도보 5분', 'HEP Five 쇼핑몰 도보 2분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '24시간 체크인',
            '주차',
            '수화물 보관',
            '스파',
        ],
        image: ['ht-27-a.webp', 'ht-27-b.webp'],
    },
    {
        id: 28,
        name: '하카타 부산야 겐큐 호텔',
        engName: 'Hakata Busanya Kenkyu Hotel',
        slug: 'hakata-busanya-kenkyu-hotel',
        type: '호텔',
        star: '4성급',
        location: '일본 후쿠오카',
        price: 220000,
        rate: 4.2,
        reviewCount: null,
        about: '하카타 역 근처의 깔끔한 객실, 접근성이 좋은 중급 호텔입니다.',
        phone: '+81 92-411-0211',
        mail: 'info@busanyakenkyu.jp',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '2-4 Hakataekichuogai, Hakata Ward, Fukuoka, 812-0012, Japan',
        landmark: ['하카타 역 도보 2분', '캐널시티 하카타 도보 5분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '24시간 체크인',
            '주차',
            '수화물 보관',
            '스파',
            '반려동물 동반',
        ],
        image: ['ht-28-a.webp', 'ht-28-b.webp'],
    },
    {
        id: 29,
        name: '호텔 닛코 후쿠오카',
        engName: 'Hotel Nikko Fukuoka',
        slug: 'hotel-nikko-fukuoka',
        type: '호텔',
        star: '4성급',
        location: '일본 후쿠오카',
        price: 250000,
        rate: 4.4,
        reviewCount: null,
        about: '하카타 중심에 위치한 국제 체인 호텔로, 쇼핑과 이동이 편리합니다.',
        phone: '+81 92-482-1111',
        mail: 'reservation@hotelnikkofukuoka.jp',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '2-18-25 Hakata Ekimae, Hakata Ward, Fukuoka 812-0011, Japan',
        landmark: ['하카타 역 도보 3분', '나카스 도보 7분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '24시간 체크인',
            '주차',
            '수화물 보관',
            '스파',
        ],
        image: ['ht-29-a.webp', 'ht-29-b.webp'],
    },
    {
        id: 30,
        name: '다낭 리틀 리버 호텔',
        engName: 'Da Nang Little River Hotel',
        slug: 'da-nang-little-river-hotel',
        type: '호텔',
        star: '4성급',
        location: '베트남 다낭',
        price: 180000,
        rate: 4.3,
        reviewCount: null,
        about: '한강강변과 다낭 대성당 가까이에 위치한 중급 호텔로 이동과 편리성이 좋습니다.',
        phone: '+84 236 389 8877',
        mail: 'info@littleriverhotel.vn',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '124-126 Bach Dang Street, Da Nang, Vietnam',
        landmark: ['한강강변 도보 5분', '다낭 대성당 차량 3분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '레스토랑',
            '24시간 체크인',
            '주차',
            '수화물 보관',
            '스파',
            '반려동물 동반',
        ],
        image: ['ht-30-a.webp', 'ht-30-b.webp'],
    },
    {
        id: 31,
        name: '푸르메르 리젠시 다낭 호텔',
        engName: 'Aurora Regency Da Nang Hotel',
        slug: 'aurora-regency-da-nang-hotel',
        type: '호텔',
        star: '5성급',
        location: '베트남 다낭',
        price: 240000,
        rate: 4.6,
        reviewCount: null,
        about: '바닷가 가까이에 위치한 리조트 스타일의 고급 호텔로 스파와 풀사이드 레스토랑이 장점입니다.',
        phone: '+84 236 393 8888',
        mail: 'info@auroraregencydanang.com',
        policies: [
            '체크인 : 15:00 | 체크아웃 : 11:00',
            '전 객실 금연 (흡연 시, 호텔 내부 규정에 따라 과금 발생)',
            '객실 내 생수 외 모든 일회용품 미제공',
            '체크인 시간 15시부터 체크아웃 11시까지 무료 주차 가능',
            '그 외 주차 시 30분당 2,000원 추가 비용 발생',
        ],
        cancellation: [
            '체크인일 기준 3일 전 17시까지 : 100% 환불',
            '체크인일 기준 3일 전 17시이후~당일 및 No-show : 환불불가',
            '취소, 환불 시 수수료가 발생할 수 있습니다',
        ],
        address: '18-20 Phan Chau Trinh, Da Nang, Vietnam',
        landmark: ['미케 비치 차량 5분', '다낭 드래곤 브리지 도보 10분'],
        service: [
            '무료 와이파이',
            '조식 제공',
            '수영장',
            '24시간 체크인',
            '주차',
            '수화물 보관',
            '스파',
            '개별 바베큐',
        ],
        image: ['ht-31-a.webp', 'ht-31-b.webp'],
    },
    // {
    //     id: 32,
    //     name: '드림인제주 독채펜션',
    //     engName: 'Dream In Jeju Pension',
    //     slug: 'dream-in-jeju-pension',
    //     type: '펜션',
    //     star: '3성급',
    //     location: '제주 서귀포시',
    //     price: 180000,
    //     rate: 4.7,
    //     reviewCount: null,
    //     about: '성산 일출봉 근처 독채 펜션으로 조용한 자연 속 휴식을 제공합니다.',
    //     phone: '064-782-xxxx',
    //     mail: 'info@dreaminjeju.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '제주특별자치도 서귀포시 성산읍 서성일로747번길 5-14',
    //     landmark: ['성산 일출봉 도보 10분'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수영장',
    //         '레스토랑',
    //         '24시간 체크인',
    //         '주차',
    //         '수화물 보관',
    //         '스파',
    //     ],
    //     image: ['pn-32-a.webp', 'pn-32-b.webp'],
    // },
    // {
    //     id: 33,
    //     name: '아쿠아뷰티크 풀빌라펜션',
    //     engName: 'Aqua Boutique Villa Pension',
    //     slug: 'aquaboutique-villa-pension-jeju',
    //     type: '펜션',
    //     star: '4성급',
    //     location: '제주 제주시',
    //     price: 200000,
    //     rate: 4.8,
    //     reviewCount: null,
    //     about: '월정리 해변 인근에 위치한 풀빌라 스타일의 펜션으로 바다 전망과 힐링 분위기를 제공합니다.',
    //     phone: '064-782-xxxx',
    //     mail: 'reserve@aquaboutique.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '제주 제주시 구좌읍 해맞이해안로 522 1층 아쿠아뷰티크 펜션',
    //     landmark: ['월정리 해변 도보 4분'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '레스토랑',
    //         '주차',
    //         '24시간 체크인',
    //         '스파',
    //         '수화물 보관',
    //         '개별 바베큐',
    //     ],
    //     image: ['pn-33-a.webp', 'pn-33-b.webp'],
    // },
    // {
    //     id: 34,
    //     name: '자유하는 펜션 제주',
    //     engName: 'Jayouhaneun Pension Jeju',
    //     slug: 'jayouhaneun-pension-jeju',
    //     type: '펜션',
    //     star: '3성급',
    //     location: '제주 제주시',
    //     price: 120000,
    //     rate: 4.3,
    //     reviewCount: null,
    //     about: '곽지해수욕장 접근성이 좋고 조용한 분위기의 펜션입니다.',
    //     phone: '064-xxxx-xxxx',
    //     mail: 'contact@jayouhaneun.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '제주 제주시 곽지해수욕장 인근',
    //     landmark: ['곽지해수욕장 도보 거리'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '주차',
    //         '수화물 보관',
    //         '레스토랑',
    //         '스파',
    //         '반려동물 동반',
    //     ],
    //     image: ['pn-34-a.webp', 'pn-34-b.webp'],
    // },
    // {
    //     id: 35,
    //     name: '서울숲스테이 게스트하우스',
    //     engName: 'Seoul Forest Stay Guesthouse',
    //     slug: 'seoul-forest-stay-guesthouse',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '서울 성동구',
    //     price: 80000,
    //     rate: 4.5,
    //     reviewCount: null,
    //     about: '성수동 서울숲 인근에 위치한 깔끔하고 조용한 게스트하우스입니다.',
    //     phone: '02-xxxx-xxxx',
    //     mail: 'stay@seoulforestgh.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '서울특별시 성동구 블루보틀코리아 인근',
    //     landmark: ['뚝섬역 도보 4분'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수화물 보관',
    //         '주차',
    //         '레스토랑',
    //         '스파',
    //         '반려동물 동반',
    //         '개별 바베큐',
    //     ],
    //     image: ['gh-35-a.webp', 'gh-35-b.webp'],
    // },
    // {
    //     id: 36,
    //     name: 'Mark’s Guest House',
    //     engName: 'Mark’s Guest House Seoul',
    //     slug: 'marks-guest-house-seoul',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '서울 마포구',
    //     price: 70000,
    //     rate: 4.4,
    //     reviewCount: null,
    //     about: '홍대지역 중심에 위치한 분위기 있는 게스트하우스.',
    //     phone: '02-xxxx-xxxx',
    //     mail: 'info@marksgh.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '서울특별시 마포구 동교로 153-6',
    //     landmark: ['홍대입구역 도보 5분'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수화물 보관',
    //         '주차',
    //         '스파',
    //         '반려동물 동반',
    //         '레스토랑',
    //         '개별 바베큐',
    //     ],
    //     image: ['gh-36-a.webp', 'gh-36-b.webp'],
    // },
    // {
    //     id: 37,
    //     name: '수송 게스트 하우스',
    //     engName: 'SooSong Guest House',
    //     slug: 'soosong-guest-house',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '서울 종로구',
    //     price: 60000,
    //     rate: 4.2,
    //     reviewCount: null,
    //     about: '도심 속 조용한 한옥 느낌이 있는 게스트하우스로 여행객에게 인기가 좋습니다.',
    //     phone: '02-xxxx-xxxx',
    //     mail: 'contact@soosonggh.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '서울특별시 종로구 율곡로 4길 59',
    //     landmark: ['종로 중심가 접근성 좋음'],
    //     service: [
    //         '무료 와이파이',
    //         '수화물 보관',
    //         '24시간 체크인',
    //         '주차',
    //         '스파',
    //         '레스토랑',
    //         '반려동물 동반',
    //     ],
    //     image: ['gh-37-a.webp', 'gh-37-b.webp'],
    // },
    // {
    //     id: 38,
    //     name: '모루헌 독채펜션',
    //     engName: 'Moruhun Private Pension',
    //     slug: 'moruhun-private-pension',
    //     type: '펜션',
    //     star: '3성급',
    //     location: '제주 서귀포시',
    //     price: 170000,
    //     rate: 4.6,
    //     reviewCount: null,
    //     about: '서귀포 귤밭 한가운데 독채로 조용한 분위기를 제공합니다.',
    //     phone: '064-xxxx-xxxx',
    //     mail: 'reserve@moruhunpension.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '제주특별자치도 서귀포시 호근로86번길 7-2',
    //     landmark: ['귤 밭 주변 한적한 환경'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수영장',
    //         '주차',
    //         '수화물 보관',
    //         '스파',
    //         '레스토랑',
    //         '개별 바베큐',
    //     ],
    //     image: ['pn-38-a.webp', 'pn-38-b.webp'],
    // },
    // {
    //     id: 39,
    //     name: '월정리 빌레왓 펜션',
    //     engName: 'Woljeongri Villewat Pension',
    //     slug: 'woljeongri- villewat-pension',
    //     type: '펜션',
    //     star: '3성급',
    //     location: '제주 제주시',
    //     price: 190000,
    //     rate: 4.7,
    //     reviewCount: null,
    //     about: '월정리 해변 가까이 위치한 독채 펜션이며 조용하고 사진 찍기 좋은 공간입니다.',
    //     phone: '064-xxxx-xxxx',
    //     mail: 'contact@villewatpension.kr',
    //     policies: [],
    //     cancellation: [],
    //     address: '제주 제주시 구좌읍 월정1길 46-15',
    //     landmark: ['월정리 해변 도보 4분'],
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수영장',
    //         '주차',
    //         '수화물 보관',
    //         '스파',
    //         '반려동물 동반',
    //         '개별 바베큐',
    //     ],
    //     image: ['pn-39-a.webp', 'pn-39-b.webp'],
    // },
    // {
    //     id: 40,
    //     name: '서울 게스트하우스 소담',
    //     engName: 'Seoul Guesthouse Sodam',
    //     slug: 'seoul-guesthouse-sodam',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '서울 종로구',
    //     price: 62000,
    //     rate: 4.2,
    //     address: '서울특별시 종로구 인사동길 33',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수화물 보관',
    //         '레스토랑',
    //         '24시간 체크인',
    //         '주차',
    //         '반려동물 동반',
    //     ],
    //     policies: '',
    //     cancellation: '',
    //     image: ['gh-40-a.webp', 'gh-39-b.webp'],
    // },
    // {
    //     id: 41,
    //     name: '서울 스테이 게스트하우스',
    //     engName: 'Seoul Stay Guesthouse',
    //     slug: 'seoul-stay-guesthouse',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '서울 마포구',
    //     price: 55000,
    //     rate: 4.0,
    //     address: '서울특별시 마포구 서교동 358-27',
    //     service: ['무료 와이파이', '조식 제공', '수화물 보관', '레스토랑', '주차', '24시간 체크인'],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 42,
    //     name: '부산 해운대 게스트하우스',
    //     engName: 'Haeundae Guesthouse Busan',
    //     slug: 'haeundae-guesthouse-busan',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '부산 해운대구',
    //     price: 58000,
    //     rate: 4.3,
    //     address: '부산광역시 해운대구 해운대로 620',
    //     service: ['무료 와이파이', '조식 제공', '수화물 보관', '주차', '24시간 체크인', '스파'],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 43,
    //     name: '부산 남포 게스트하우스',
    //     engName: 'Nampo Guesthouse Busan',
    //     slug: 'nampo-guesthouse-busan',
    //     type: '게스트하우스',
    //     star: '2성급',
    //     location: '부산 중구',
    //     price: 49000,
    //     rate: 4.1,
    //     address: '부산광역시 중구 광복로 45',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '주차',
    //         '레스토랑',
    //         '수화물 보관',
    //         '반려동물 동반',
    //         '24시간 체크인',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 44,
    //     name: '강원 설악 빌라',
    //     engName: 'Seorak Villa',
    //     slug: 'seorak-villa',
    //     type: '빌라',
    //     star: '3성급',
    //     location: '강원 속초시',
    //     price: 142000,
    //     rate: 4.5,
    //     address: '강원특별자치도 속초시 설악산로 127',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수영장',
    //         '주차',
    //         '스파',
    //         '개별 바베큐',
    //         '24시간 체크인',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 45,
    //     name: '강원 평창 빌라',
    //     engName: 'Pyeongchang Villa',
    //     slug: 'pyeongchang-villa',
    //     type: '빌라',
    //     star: '3성급',
    //     location: '강원 평창군',
    //     price: 156000,
    //     rate: 4.6,
    //     address: '강원특별자치도 평창군 대관령면 89',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '스파',
    //         '수영장',
    //         '주차',
    //         '개별 바베큐',
    //         '24시간 체크인',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 46,
    //     name: '대전 힐링 빌라',
    //     engName: 'Daejeon Healing Villa',
    //     slug: 'daejeon-healing-villa',
    //     type: '빌라',
    //     star: '3성급',
    //     location: '대전 유성구',
    //     price: 128000,
    //     rate: 4.4,
    //     address: '대전광역시 유성구 온천북로 12',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수화물 보관',
    //         '레스토랑',
    //         '스파',
    //         '주차',
    //         '수영장',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 47,
    //     name: '대전 라임 빌라',
    //     engName: 'Daejeon Lime Villa',
    //     slug: 'daejeon-lime-villa',
    //     type: '빌라',
    //     star: '3성급',
    //     location: '대전 서구',
    //     price: 134000,
    //     rate: 4.3,
    //     address: '대전광역시 서구 둔산중로 56',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '주차',
    //         '24시간 체크인',
    //         '스파',
    //         '개별 바베큐',
    //         '수영장',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 48,
    //     name: '전주 한옥마을 숙소 소담채',
    //     engName: 'Sodamchae Hanok Stay',
    //     slug: 'sodamchae-hanok-stay',
    //     type: '한옥',
    //     star: '3성급',
    //     location: '전주 완산구',
    //     price: 96000,
    //     rate: 4.6,
    //     address: '전라북도 전주시 완산구 기린대로 55',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수화물 보관',
    //         '주차',
    //         '스파',
    //         '반려동물 동반',
    //         '개별 바베큐',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 49,
    //     name: '전주 한옥 스테이 청연재',
    //     engName: 'Cheongyeonjae Hanok Stay',
    //     slug: 'cheongyeonjae-hanok-stay',
    //     type: '한옥',
    //     star: '3성급',
    //     location: '전주 완산구',
    //     price: 99000,
    //     rate: 4.7,
    //     address: '전라북도 전주시 완산구 향교길 19',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '주차',
    //         '수화물 보관',
    //         '24시간 체크인',
    //         '스파',
    //         '개별 바베큐',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 50,
    //     name: '수원 한옥 스테이 화홍재',
    //     engName: 'Hwajeongjae Hanok Stay',
    //     slug: 'hwajeongjae-hanok-stay',
    //     type: '한옥',
    //     star: '3성급',
    //     location: '수원 팔달구',
    //     price: 91000,
    //     rate: 4.5,
    //     address: '경기도 수원시 팔달구 화서문로 35',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '수화물 보관',
    //         '주차',
    //         '반려동물 동반',
    //         '스파',
    //         '개별 바베큐',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 51,
    //     name: '수원 한옥마을 채향재',
    //     engName: 'Chaehyangjae Hanok Stay',
    //     slug: 'chaehyangjae-hanok-stay',
    //     type: '한옥',
    //     star: '3성급',
    //     location: '수원 장안구',
    //     price: 94000,
    //     rate: 4.4,
    //     address: '경기도 수원시 장안구 영화동 89',
    //     service: [
    //         '무료 와이파이',
    //         '조식 제공',
    //         '주차',
    //         '레스토랑',
    //         '수화물 보관',
    //         '24시간 체크인',
    //         '개별 바베큐',
    //     ],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 52,
    //     name: '서울 캡슐호텔 타임',
    //     engName: 'Time Capsule Hotel Seoul',
    //     slug: 'time-capsule-hotel-seoul',
    //     type: '캡슐호텔',
    //     star: '2성급',
    //     location: '서울 강남구',
    //     price: 42000,
    //     rate: 4.2,
    //     address: '서울특별시 강남구 봉은사로 512',
    //     service: ['무료 와이파이', '수화물 보관', '주차', '조식 제공', '24시간 체크인', '스파'],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 53,
    //     name: '부산 캡슐호텔 더포드',
    //     engName: 'The Pod Capsule Hotel Busan',
    //     slug: 'the-pod-capsule-hotel-busan',
    //     type: '캡슐호텔',
    //     star: '2성급',
    //     location: '부산 해운대구',
    //     price: 39000,
    //     rate: 4.1,
    //     address: '부산광역시 해운대구 구남로 45',
    //     service: ['무료 와이파이', '조식 제공', '수화물 보관', '주차', '24시간 체크인', '스파'],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 54,
    //     name: '제주 캡슐호텔 플레이스',
    //     engName: 'Capsule Place Jeju',
    //     slug: 'capsule-place-jeju',
    //     type: '캡슐호텔',
    //     star: '2성급',
    //     location: '제주 제주시',
    //     price: 37000,
    //     rate: 4.0,
    //     address: '제주특별자치도 제주시 서사로 67',
    //     service: ['무료 와이파이', '조식 제공', '주차', '수화물 보관', '24시간 체크인', '스파'],
    //     policies: '',
    //     cancellation: '',
    // },
    // {
    //     id: 55,
    //     name: '강원 캡슐호텔 포레스트',
    //     engName: 'Forest Capsule Hotel',
    //     slug: 'forest-capsule-hotel',
    //     type: '캡슐호텔',
    //     star: '2성급',
    //     location: '강원 춘천시',
    //     price: 36000,
    //     rate: 4.2,
    //     address: '강원특별자치도 춘천시 명동길 13',
    //     service: ['무료 와이파이', '조식 제공', '수화물 보관', '주차', '24시간 체크인', '스파'],
    //     policies: '',
    //     cancellation: '',
    // },
];
